Asher hbv
naobservatory/p2ra pull request #102
Opened 2023-05-18 16:52 UTC by asherps

Created an ohio-specific acute hbv estimate for 2021.

2023-05-19 19:24 UTC, jeffkaufman requested changes

2023-05-19 19:24 UTC, jeffkaufman commented on pathogen_properties.py
> +        print(states)
rm

2023-05-19 19:24 UTC, jeffkaufman commented on pathogen_properties.py
> +        return dataclasses.replace(self, people=self.people - other.people)
`other` needs to end up in `inputs`

2023-05-19 19:24 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +from pathogen_properties import *
Your changes to rhinovirus.py don't belong in this PR.

In general, when you start a new PR that should look like:

```
git checkout main
git branch -b asher-some-feature
...
```

I suspect you skipped the `git checkout main` here?

2023-05-19 19:24 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +from pathogen_properties import *
Same with your `pathogen_properties.py` changes.  I think this PR should only include `hbv.py`?

2023-05-23 18:13 UTC, jeffkaufman requested changes

2023-05-23 18:13 UTC, jeffkaufman commented on pathogens/hav.py
Why are you deleting `hav.py`?  This PR shouldn't affect `hav.py` either way.

2023-05-23 18:13 UTC, jeffkaufman commented on pathogens/hbv.py
> +    # cases still have an acute phase in which they shed.
@simonleandergrimm does this seem reasonable to you?  (Looks fine to me)

2023-05-23 19:11 UTC, asherps commented on pathogens/hbv.py
> +    # cases still have an acute phase in which they shed.
I think if this seems reasonable to you, I think it's good to go? I don't think there are any other changes I need to make (there was no reason to remove hav, as jeff noted above, but it shouldnt matter either way if this is merged into main)

2023-05-23 19:43 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    # cases still have an acute phase in which they shed.
This isn't needed. If you look at the table more specifically, the table gives **acute** and **total** numbers. The authors then say that
```
Total hepatitis equals all hepatitis B cases,both "acute" and "chronic".
```
So just using total is the way to go (which Asher is already doing). I told @asherps to change the wording of the comment to not make it sound like there is manual addition.

2023-05-24 00:34 UTC, simonleandergrimm requested changes

2023-05-24 00:34 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    # new chronic cases for that year.
What do you mean by true number of new chronic cases here?

2023-05-24 00:34 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    # new chronic cases for that year.
I would also shorten this paragraph to one or two sentences, it's a bit wordy atm.

2023-05-24 18:10 UTC, simonleandergrimm reviewed
The estimate looks good, I just have a question on your comment on line 70.

2023-05-24 18:10 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    # approximately the number of new chronic cases for that year.
We talked about this yesterday, but I am unsure what you are arguing for or against here, could you explain?

```
However, the reported chronic incidence in any given year should still be approximately the number of new chronic cases for that year.
```
What do you mean by this? I would think reported incidence very likely underestimates the true number of true cases.

2023-05-24 18:29 UTC, asherps commented on pathogens/hbv.py
> +    # approximately the number of new chronic cases for that year.
I'm arguing that chronic cases should be counted because they're our best guess at true chronic incidence for a current year, even some of the new chronic cases identified are from years ago. I updated the comment again, see what you think

2023-05-24 19:40 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    # cases for 2021
Added it to my agenda to talk through this tomorrow

2023-05-30 18:51 UTC, simonleandergrimm commented
Superseded by #122 . I will thus close this PR.

2023-05-30 18:51 UTC, closed without merging