Asher hav
naobservatory/p2ra pull request #109
Opened 2023-05-23 15:14 UTC by asherps

2023-05-23 16:04 UTC, simonleandergrimm commented
@asherps, as of now, this is failing checks. Could you reassign this to me once the checks pass?

2023-05-23 16:04 UTC, simonleandergrimm requested changes
Doesn't pass checks.

2023-05-24 17:30 UTC, asherps commented on pathogens/hav.py
> +        ).to_rate(us_population(year=2021, state="Ohio", county=row[0]))
Thanks for pointing this out. This was happening because my return dictionary entries method was only returning the first entry. However, I don't know how to fix this to return every entry of the dictionary separately. I can return them as a list, but estimate_incidences can't currently return a list. @jeffkaufman, do you know what I should do? Thanks

2023-05-24 19:36 UTC, simonleandergrimm requested changes
Nearly done! Left some comments on the end of the code regarding CSV parsing. Also, please pull the newest version from main, I changed the HAV file yesterday.

2023-05-24 19:43 UTC, asherps commented on pathogens/hav.py
> +        estimates.append((ohio_county_hav_incidences[item]))
I think this problem was just because of the print statement which I left in after debugging? I removed the print statement and it displays normally now. See what you think

2023-05-24 19:43 UTC, asherps commented on pathogens/hav.py
> +        estimates.append((ohio_county_hav_incidences[item]))
Thanks

2023-05-25 14:51 UTC, simonleandergrimm commented on pathogens/hav.py
> +# Data source: https://odh.ohio.gov/know-our-programs/Hepatitis-Surveillance-Program/Hepatitis-A-Statewide-Community-Outbreak/
I only spotted this now, but did you try to get more finely resolved data, as originally discussed in my Twist message? Treating case numbers from 4.5y as occurring uniformly is a pretty big assumption. I can look into this some more myself, but wanted to ask this beforehand.

2023-05-25 14:52 UTC, simonleandergrimm reviewed
Left one question on finding data that is more time-resolved.

2023-05-25 20:33 UTC, asherps commented on pathogens/hav.py
> +# Data source: https://odh.ohio.gov/know-our-programs/Hepatitis-Surveillance-Program/Hepatitis-A-Statewide-Community-Outbreak/
Couldn't find more time resolved data in a 10 minute pass. Possible it exists or we could get it from them over email

2023-05-30 19:02 UTC, simonleandergrimm commented
Superseded by #121

2023-05-30 19:02 UTC, closed without merging