Fit covid and norovirus to Rothman MGS
naobservatory/p2ra pull request #112
Opened 2023-05-23 20:31 UTC by dp-rice

Refactor and generalize the fitting code to work with covid and norovirus incidence data and Rothman MGS (partially resolves #106). Also add some tests for `stats.py` (resolves #57).

Removes `fit_covid.py`. Now all fitting is done by `fit_rothman.py` which outputs `tsv` files with posterior samples (not in the repo) and prints:
```
$  ./fit_rothman.py 2> /dev/null

-------------------------------------------
sars_cov_2 relative abundance per incidence
-------------------------------------------
Posterior arithmetic mean:
6.0e-12
Posterior geometric mean:
5.8e-12
Posterior quantiles:
     5%        25%        50%        75%        95%
4.0e-12    5.0e-12    5.8e-12    6.7e-12    8.5e-12

------------------------------------------
norovirus relative abundance per incidence
------------------------------------------
Posterior arithmetic mean:
1.1e-08
Posterior geometric mean:
1.1e-08
Posterior quantiles:
     5%        25%        50%        75%        95%
8.2e-09    9.7e-09    1.1e-08    1.3e-08    1.5e-08
```

2023-05-23 20:36 UTC, dp-rice commented
@jeffkaufman, only if you have time before you go.

Also, I added and removed a large binary file from the repo. I hope that that doesn't make things too slow since it shouldn't show up in any diffs if I squash and merge.

2023-05-24 02:14 UTC, jeffkaufman requested changes
just minor stuff

2023-05-24 02:14 UTC, jeffkaufman commented on fit_rothman.py
>      title = f"{pathogen} relative abundance at 1% prevalence"
I think the at `1% prevalence` is now wrong in cases where we're working on incidence?

2023-05-24 02:14 UTC, jeffkaufman commented on stats.py
> +    df["incidence_per100k"] = np.exp(df["theta"])
I thought the model was going to be agnostic on whether it was being given an incidence or a prevalence?  (here and below)

2023-05-24 19:53 UTC, dp-rice commented
@jeffkaufman if you have time before you go, could you please take a look at the (small) change I made to `pathogen_properties.py`?

2023-05-24 20:07 UTC, jeffkaufman commented
Change to pathogen_properties LGTM!

2023-05-24 20:12 UTC, merged