Simon HBV (supersedes #102)
naobservatory/p2ra pull request #122
Opened 2023-05-30 18:39 UTC by simonleandergrimm

This pull request supersedes #102. It includes:
 - Asher's original addition total (acute + chronic) reported Hep B cases from 2021 in Ohio, now split into acute and chronic cases.
 - Added a CDC underreporting factor to scale up reported acute cases from Ohio.
 - Added CDC-provided reported chronic Hep B cases.

2023-05-30 18:51 UTC, simonleandergrimm commented on pathogens/hbv.py
> +# chronic Hep B disease burden.
@jeffkaufman Let me know if you agree.

2023-06-01 18:49 UTC, jeffkaufman requested changes

2023-06-01 18:49 UTC, jeffkaufman commented on pathogens/hbv.py
> +        ohio_reported_chronic_incidence_2021,
This doesn't seem right to me -- why aren't we summing the acute and chronic cases?

2023-06-02 15:28 UTC, simonleandergrimm commented on pathogens/hbv.py
> +        ohio_reported_chronic_incidence_2021,
Discussed in person

2023-06-02 18:14 UTC, jeffkaufman requested changes

2023-06-02 18:14 UTC, jeffkaufman commented on pathogens/hbv.py
> +        cdc_reported_chronic_2019,
Where is this defined?  Does this change pass tests?

2023-06-02 20:11 UTC, jeffkaufman approved these changes

2023-06-02 20:24 UTC, merged