Simon rhinovirus
naobservatory/p2ra pull request #124
Opened 2023-05-31 16:05 UTC by simonleandergrimm

Supersedes #66 

The main change is that I cleaned up the code and restructured the order of variables.

2023-06-01 19:07 UTC, jeffkaufman requested changes

2023-06-01 19:07 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
Can we do the same approach here I suggested at https://github.com/naobservatory/p2ra/pull/123#discussion_r1213552516 ?

2023-06-01 19:07 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    "40+": 4_965_022  # subtracting <40yo population from total population
I'd delete the 40+ entry; see rest of comment below.

2023-06-01 19:07 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +rhinovirus_1970s_tecumseh_based_la_estimate = (
Comment that we're assuming that people still get the same number of annual rhinoviruses for their age as they did in Tecumseh in the 70s, and adjusting it to represent the difference in age breakdown between the two contexts

2023-06-02 17:30 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +rhinovirus_1970s_tecumseh_based_la_estimate = (
Added

2023-06-02 17:30 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +
done

2023-06-02 17:30 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +)
Done

2023-06-02 17:53 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +
Doing this i currently get the following error. I will look more into this later today or on Monday.
```
Traceback (most recent call last):
  File "/Users/simongrimm/code/p2ra/summarize.py", line 5, in <module>
    import pathogens
  File "/Users/simongrimm/code/p2ra/pathogens/__init__.py", line 12, in <module>
    pathogens[pathogen_name] = importlib.import_module(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/simongrimm/code/p2ra/pathogens/rhinovirus.py", line 105, in <module>
    ) - sum(la_county_populations_by_age.values())
TypeError: unsupported operand type(s) for +: 'int' and 'Population'
```

2023-06-02 17:53 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +
@simonleandergrimm for my own awareness

2023-06-03 16:21 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +
Fixed this by adding an `__radd__` method to `Population`. I now run into an issue with `mypy`, @jeffkaufman happy to look at this on Monday.

Running mypy to check types...
pathogen_properties.py:466: error: Name "Number" already defined on line 301  [no-redef]
    class Number(Variable):
    ^
pathogens/rhinovirus.py:105: error: No overload variant of "sum" matches argument types "dict_values[str, Population]",
"Number"  [call-overload]
    ) - sum(la_county_populations_by_age.values(), start=Number(number=0))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pathogens/rhinovirus.py:105: note: Possible overload variants:
pathogens/rhinovirus.py:105: note:     def sum(Iterable[bool], /, start: int = ...) -> int
pathogens/rhinovirus.py:105: note:     def [_SupportsSumNoDefaultT <: _SupportsSumWithNoDefaultGiven] sum(Iterable[_SupportsSumNoDefaultT], /) -> Union[_SupportsSumNoDefaultT, Literal[0]]
pathogens/rhinovirus.py:105: note:     def [_AddableT1 <: SupportsAdd[Any, Any], _AddableT2 <: SupportsAdd[Any, Any]] sum(Iterable[_AddableT1], /, start: _AddableT2) -> Union[_AddableT1, _AddableT2]
Found 2 errors in 2 files (checked 24 source files)
FAIL: types

2023-06-03 16:26 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +
*sum() likely trips up due to me defining start as `Number(number=0)`.

2023-06-05 13:28 UTC, merged