Simon CMV (supersedes #48)
naobservatory/p2ra pull request #126
Opened 2023-05-31 20:30 UTC by simonleandergrimm

Supersedes #48 
 - Edited comments
 - Dropped active estimate of CMV. @jeffkaufman, feel free to spend 10 mins to look at #48 and the active estimate therein. I currently do not want to spend >30 min on evaluating and potentially improving upon this estimate, though happy to have my mind changed.

2023-06-01 19:18 UTC, jeffkaufman requested changes

2023-06-01 19:18 UTC, jeffkaufman commented on pathogens/CMV.py
> +ger_adult_seroprevalence_estimate = Prevalence(
Normally we abbreviate Germany as `de`, since that it's (3166-1 alpha 2) country code

2023-06-01 19:18 UTC, jeffkaufman commented on pathogens/CMV.py
> +    infections_per_100k=0.567 * 100000,
100_000

2023-06-01 19:18 UTC, jeffkaufman commented on pathogens/CMV.py
> +    end_date="2004",
Is there no more recent NHANES data covering CMV?

2023-06-02 14:31 UTC, simonleandergrimm commented on pathogens/CMV.py
> +    end_date="2004",
No there isn't, they stopped taking antibody measurements for all participants after 2004. The only available data is for [1-5yo in 2011/2012 ](https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/CMV_G.htm) and [2017-2020](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_CMV.htm)

2023-06-02 18:11 UTC, jeffkaufman approved these changes

2023-06-02 18:11 UTC, jeffkaufman commented on pathogens/cmv.py
> +    country="US",
`"United States"`

2023-06-02 18:11 UTC, jeffkaufman commented on pathogens/cmv.py
> +    country="US",
`"United States"`

2023-06-02 18:11 UTC, jeffkaufman commented on pathogens/cmv.py
> +    country="US",
`"United States"`

2023-06-02 19:52 UTC, merged