Simon ebv
naobservatory/p2ra pull request #144
Opened 2023-06-05 18:59 UTC by simonleandergrimm

Curious if you have suggestions for making the code more efficient, particularly by dropping repetitions.

2023-06-05 19:57 UTC, jeffkaufman requested changes
Initial comments

2023-06-05 19:57 UTC, jeffkaufman commented on pathogens/ebv.py
> +    age_6_17: Dict[str, List] = {
nit: `Dict` and `List` are obsolete now; you can just use `dict` and `list`

2023-06-05 19:57 UTC, jeffkaufman commented on pathogens/ebv.py
> +    age_6_17: Dict[str, List] = {
You should provide `list[float]` or whatever the list contains.

2023-06-05 19:57 UTC, jeffkaufman commented on prevalence-data/ebv_6_19_nhanes_2003_2010.csv
> +Total ,Mexican American ,2586 ,  88 ,    84 ,     90
It looks to me like they measured ~equal-size samples from these three groups, but this doesn't match the ethnic breakdown of the US overall, or of any of our regions.  I expected something to scale this down to represent that more than 1/3 of Americans are white?

2023-06-05 19:57 UTC, jeffkaufman commented on pathogens/ebv.py
> +        age = row[0].strip()
Here's a go at a tidier implementation:

```
estimate_weights: list[tuple[Prevalence, Population]] = []
for row in csv.reader(inf):
  age, ethnicity, size, mean, ci_low, ci_high = [x.strip() for x in row]
  if age in ["Age", "Total"]: continue

  prevalence = Prevalence(
        infections_per_100k=float(mean) * 100_000,
        confidence_interval=(float(ci_low) * 100_000, float(ci_high) * 100_000),
        coverage_probability=0.95,
        number_of_participants=size,
        country="United States",
        start_date="2003",
        end_date="2010",
        active=Active.LATENT,
        source=EBV_US_2003_2010_SEROPREVALENCE,
  )
  population = Population( ... ) # look up population for age and ethnicity, treating 18-19 as all adults
  estimate_weights.append((prevalence, population))

us_seroprevalence_2003_2010 = Prevalence.weightedAverageByPopulation(estimate_weights)
```

2023-06-05 21:01 UTC, simonleandergrimm commented on pathogens/ebv.py
> +        age = row[0].strip()
Could use this population data: https://data.census.gov/table?q=2021++acs+race&tid=ACSST1Y2021.S0501

Discuss more with jeff tomorrow.

2023-06-07 17:22 UTC, simonleandergrimm commented
@jeffkaufman The current script is failing type errors. I am not super fast in addressing these, and it likely makes sense for you to fix them either alone or in pair programming. This isn't a high priority, though.

2023-06-15 17:09 UTC, jeffkaufman requested changes

2023-06-15 17:09 UTC, jeffkaufman commented on pathogens/ebv.py
> +    # Seroprevalence should remain constant, so we can extrapolate from 1983
You've already assumed seroprevalance should be constant; I think the main thing to call out here is you're assuming that the population breakdown is constant.

2023-06-15 17:09 UTC, jeffkaufman commented on pathogens/ebv.py
> +    with open(prevalence_data_filename(f"{race}.csv")) as inf:
Here's where to put your comment saying where and how you got the CSVs

2023-06-16 16:14 UTC, simonleandergrimm commented on pathogens/ebv.py
> +    denmark_seroprevalence = Prevalence.weightedAverageByPopulation(
This didn't work for me, instead I used thefollowing code:

    seroprevalence_population_pairs = [
        (denmark_seroprevalences[age], denmark_populations[age])
        for age in denmark_populations.keys()
    ]

    return Prevalence.weightedAverageByPopulation(
        *seroprevalence_population_pairs
    )

2023-06-16 16:24 UTC, simonleandergrimm commented on pathogens/ebv.py
> +    with open(prevalence_data_filename("DenmarkPopulationData.csv")) as file:
Done

2023-06-16 19:12 UTC, jeffkaufman requested changes

2023-06-16 19:12 UTC, jeffkaufman commented on pathogens/ebv.py
> +    )
How about:

```
return Prevalence.weightedAverageByPopulation(
        *[(denmark_seroprevalences[age], denmark_populations[age])
           for age in denmark_populations.keys()]
    )
```

Naming the intermediate variable doesn't help much

2023-06-16 19:12 UTC, jeffkaufman commented on pathogens/ebv.py
> +    # Seroprevalence should remain constant, so we can extrapolate from 1983
You're still not calling out the key (and quite minor) assumption: the age breakdown of the population hasn't changed much from 2023 to 2020/2021.

2023-06-16 19:12 UTC, jeffkaufman commented on pathogens/ebv.py
> +        # Age tables were renamed to [black/white/latino]_age_cohorts.csv.
Needs to be more specific.  Did you take "PCT12I: SEX BY SINGLE-YEAR AGE (WHITE ALONE, NOT HISPANIC OR LATINO)", "PCT12H: SEX BY SINGLE-YEAR AGE (HISPANIC OR LATINO)", and "PCT12B: SEX BY SINGLE-YEAR AGE (BLACK OR AFRICAN AMERICAN ALONE)"?

(Especially wanting to make sure you didn't take "PCT12A: SEX BY SINGLE-YEAR AGE (WHITE ALONE)" since that will include hispanic whites.)

2023-06-16 22:07 UTC, simonleandergrimm commented on pathogens/ebv.py
> +    # Seroprevalence should remain constant, so we can extrapolate from 1983
Ah I misunderstood, thanks for the pointer.

2023-06-16 22:16 UTC, simonleandergrimm commented on pathogens/ebv.py
> +        # Age tables were renamed to [black/white/latino]_age_cohorts.csv.
Appreciate the attention here, I indeed picked PCT12A, not PCT12I. Fixed.

2023-06-19 14:56 UTC, jeffkaufman approved these changes

2023-06-19 14:56 UTC, jeffkaufman commented on pathogens/ebv.py
> +        # (min_age, max_age) -> people within that age range
doesn't look done?

2023-06-19 14:56 UTC, jeffkaufman commented on pathogens/ebv.py
> +        # Data is downloaded from this results page: "hhttps://data.census.gov/table?q=Annual+Estimates+of+the+Resident+Population+by+Single+Year&g=010XX00US&tid=DECENNIALDHC2020.PCT12A".
`hhttps` -> `https`

2023-06-19 20:25 UTC, merged