Simon hep b c extension
naobservatory/p2ra pull request #154
Opened 2023-06-12 18:05 UTC by simonleandergrimm

- Switched to using the acute Hep C CDC estimate from 2019 instead of the 2020 estimate. The CDC underreporting factors in 2020 for Hepatitis B and C were the same as in 2019, which seems wrong given the pandemic should have impacted case reporting quite a bit.
- Extrapolated acute and chronic Hep B, and acute Hep C estimates to 2019-2021.

2023-06-15 17:20 UTC, jeffkaufman requested changes
looks good!

2023-06-15 17:20 UTC, jeffkaufman commented on pathogens/hbv.py
> +    chronic_2019 = dataclasses.replace(
Why do we need a 2019 estimate?

2023-06-15 17:20 UTC, jeffkaufman commented on pathogens/hbv.py
> +    acute_2020 = dataclasses.replace(
comment here about why the extrapolation is ok

2023-06-15 17:20 UTC, jeffkaufman commented on pathogens/hcv.py
> +    estimates = [estimated_chronic_us_2013_2016]
just `return [estimated_chronic_us_2013_2016]`

2023-06-15 19:54 UTC, jeffkaufman commented on pathogens/hcv.py
> +    estimates = [estimated_chronic_us_2013_2016]
Actually, we may want to return `[]` here since `estimated_chronic_us_2013_2016` won't match any of our mgs samples

2023-06-16 14:52 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    chronic_2019 = dataclasses.replace(
We do not, I removed it!

2023-06-16 15:17 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    estimates = [estimated_chronic_us_2013_2016]
I looked into the acute case numbers of Hep C (https://www.cdc.gov/hepatitis/statistics/2020surveillance/hepatitis-c/figure-3.1.htm), and they have ticked up slightly in the past few years. Mortality, on the other hand, has dropped slightly (https://www.cdc.gov/hepatitis/statistics/2020surveillance/hepatitis-c/table-3.7.htm). On balance, I think it's unlikely that the chronic rate dropped or increased from 1% in 2016 by more than 0.2 percentage points.

I thus extrapolated the estimate after all.

2023-06-16 19:03 UTC, jeffkaufman commented on pathogens/hbv.py
> +    acute_2020 = dataclasses.replace(
Also say something about why you wouldn't expect the covid 19 pandemic to affect hbv incidence (or why you do think it probably affected it but you're extrapolating anyway)

2023-06-16 22:05 UTC, merged