Simon aav update
naobservatory/p2ra pull request #170
Opened 2023-06-21 18:11 UTC by simonleandergrimm

@jeffkaufman Let me know if one PR for AAV 5 and 6 is fine, or if I should have separated these.

2023-06-22 14:55 UTC, jeffkaufman approved these changes

2023-06-22 14:55 UTC, jeffkaufman commented on pathogens/aav5.py
> +    # global weighted average of AAV5 seroprevalence in people with HA was 29.
nit: wrapping on a decimal point is hard to distinguish from end-of-sentence

2023-06-22 15:00 UTC, jeffkaufman commented on pathogens/aav5.py
> +    # "Factoring in the prevalence of HA in the countries being assayed, the
> Factoring in the prevalence of HA in the countries being assayed

That's a weird thing to do for our purposes.  Why not use the 34.8 global non-weighted average?

2023-06-22 15:01 UTC, jeffkaufman requested changes
Since this source also has AAV8 and AAVrh10, why not include them too?

2023-06-26 18:29 UTC, simonleandergrimm commented
@jeffkaufman Flagging that this is still open.

2023-06-26 19:15 UTC, jeffkaufman approved these changes

2023-06-26 19:52 UTC, merged