Created AAV estimates for Denmark 2015-2018
naobservatory/p2ra pull request #192
Opened 2023-06-30 14:09 UTC by simonleandergrimm

Took the weigthed average of seroprevalence measurements in Northern European study participants, treating it as a Denmark estimate. Then extrapolated 2022 estimate to 2015-2018.

2023-07-05 14:26 UTC, jeffkaufman requested changes

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +    }
You're just keying two pieces of data by country, so the extra layer of hashing isn't giving you anything except an implication that there might be multiple estimates for a country and more awkward retrieval API

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +            pairs.append(
Instead of:

```
for country, vals in seroprevalence_by_country.items():
        for n_participants, seroprevalence in vals.items():
```

you can now do:

```
for country, (n_participants, seroprevalence) in ...
```

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +    pairs: list[tuple[Prevalence, Population]] = []
`pairs` -> `prevalence_population_pairs`

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +            )
Probably simpler to use a list comprehension:

```
prevalence_population_pairs = [
    (Prevalence(...), Population(...))
    for country, (n_participants, seroprevalence) in ...
]
```

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +            )
In general, anytime you're turning one collection into another collection with the same number of elements, and don't have any logic or complicated code inside, a list comprehension is a good bet

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +    return dataclasses.replace(
I think this would be clearer as `northern_european_average_seroprevalence()`, with the extrapolation to denmark in `estimate_prevalences`.  And if the extrapolation became complex, I would want to put that into a third method.

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +        denmark_extrapolated_seroprevalence(),
I would be a bit happier with:

```
dk_2022 = denmark_extrapolated_seroprevalence()
dk_2015 = dataclasses.replace(dk_2022, ...)
...
```

This has two advantages:

1. It makes it clearer how you are changing the date, 2022 to what?
2. It doesn't require running denmark_extrapolated_seroprevalence many times (which doesn't matter this case, because the method is very fast, but it still looks slightly weird to me to see an idempotent method called so many times)

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +    # Taking weighted average of Northern European AAV-2 seropositivity
This should say what you are weighting your average by.

2023-07-05 14:26 UTC, jeffkaufman commented on pathogens/aav2.py
> +                        people=n_participants,
Why are you weighting by number of participants?

2023-07-05 15:19 UTC, simonleandergrimm commented on pathogens/aav2.py
> +                        people=n_participants,
I assume that the difference in seroprevalences between countries is largely driven by the small sample sizes, not by in-between-country differences. 

I'm accounting for this noise by weighting seroprevalence measurements by their sample size.

2023-07-05 15:29 UTC, simonleandergrimm commented on pathogens/aav2.py
> +        denmark_extrapolated_seroprevalence(),
I instead did the following:
```
    # Extrapolating Northern European 2022 estimate to Denmark, backward in
    # time to 2015-2018:
    northern_europe_2022 = northern_european_average_seroprevalence()
    dk_2015 = dataclasses.replace(
        northern_europe_2022,
        date_source=Variable(date="2015"),
        location_source=Variable(country="Denmark"),
    )
   ...
```

2023-07-05 19:04 UTC, jeffkaufman commented
I see several points marked as "resolved" but without the underlying change made; do you need to push?

2023-07-05 20:21 UTC, jeffkaufman commented on pathogens/aav2.py
> +    seroprevalence_by_country = {
looks not done?

2023-07-05 20:23 UTC, jeffkaufman commented on pathogens/aav5.py
> +
That seems unlikely to me?  5.9% with 17 people is 1/17, and if the UK were actually at a level near France or Germany you'd expect 5/17 or 6/17.  @dp-rice ?

2023-07-05 20:23 UTC, jeffkaufman commented on pathogens/aav6.py
> +    # country differences.
less worried about this one, since they're closer

2023-07-05 20:24 UTC, jeffkaufman commented on pathogens/aav2.py
> +    # country differences.
this one also seems fine

2023-07-06 13:51 UTC, simonleandergrimm commented on pathogens/aav5.py
> +
Yeah, you are right about this potentially being wrong. I could change this to a more conservative statement, like so:

"We aim to estimate AAV prevalence in a population that comes as close as possible to the Danish population. To do so, we're aggregating seroprevalence measurements from Northern European countries (France, UK, Germany), weighted by their participant counts. These measurements are from the same study as the one used above."

2023-07-06 13:54 UTC, simonleandergrimm commented on pathogens/aav2.py
> +    seroprevalence_by_country = {
Missed this, sorry!

2023-07-06 14:01 UTC, simonleandergrimm commented on pathogens/aav5.py
> +
@jeffkaufman Let me know what you think. I can ping Dan again if his thoughts would be most useful.

2023-07-07 14:19 UTC, jeffkaufman commented on pathogens/aav5.py
> +
I think it's not a big deal, and there's no reason to expect Denmark to be especially close to the UK

2023-07-07 14:19 UTC, jeffkaufman approved these changes

2023-07-07 21:12 UTC, merged