Hsv 2
naobservatory/p2ra pull request #22
Opened 2023-04-24 17:32 UTC by simonleandergrimm

2023-04-24 18:44 UTC, jeffkaufman requested changes

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    enveloped=Enveloped.NON_ENVELOPED,
I thought HSV was enveloped?

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    infections_per_100k=0.102 * 100_000,
Where does 0.102 come from?  I think this should be `infections_per_100k= 478/2813 * 100_000`?

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    number_of_participants=3710,
What would you think of `2813` (positive + negative) since 3710 includes the indeterminate and missing results?

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    confidence_interval=(18.1 * 1e6, 19.0 * 1e6),
track that 18.1 and 19.0 represent the first and third quartiles ("We used Monte Carlo simulation to generate 10,000 input parameter sets for age and sex subpopulations and summarized our estimates by their median; uncertainty intervals for these estimates are characterized by their first (Q1) and third (Q3) quartiles. ...  Q1 = 18.1, Q3 = 19.0")

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    date="2018",
The analysis is 2018, but the data is older: "Using NHANES data from the 2011–2014 and 2015–2018 NHANES cycles..."

2023-04-24 18:44 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +us_population_2018 = Population(
This is the wrong population: "We estimated a total of 18.6 (Q1 = 18.1, Q3 = 19.0) million prevalent genital herpes infections in 2018 among 18- to 49-year-olds overall caused by HSV-2".  You need to divide 18.6M by the number of 18-49yo Americans.

2023-04-24 19:58 UTC, simonleandergrimm commented on pathogens/hsv_2.py
> +    enveloped=Enveloped.NON_ENVELOPED,
In clinical trials you often use method where you use drop-outs "against" you: https://en.wikipedia.org/wiki/Intention-to-treat_analysis

I have no strong feelings about this, let me know what you prefer

2023-04-24 19:59 UTC, simonleandergrimm commented on pathogens/hsv_2.py
> +    infections_per_100k=0.102 * 100_000,
will fix

2023-04-24 19:59 UTC, simonleandergrimm commented on pathogens/hsv_2.py
> +    number_of_participants=3710,
In clinical trials you often use method where you use drop-outs "against" you: https://en.wikipedia.org/wiki/Intention-to-treat_analysis

I have no strong feelings about this, let me know what you prefer

2023-04-25 02:20 UTC, jeffkaufman requested changes

2023-04-25 02:20 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    number_of_participants=3710,
I don't think that makes sense here:

* In a clinical trial drop-outs could be casually downstream from what you're trying to test
* In a clinical trial you're voluntarily taking on a higher burden of proof
* Erring on the low side when estimating `infections_per_100k` isn't "against us".  If anything it's "for us" because it gives a more optimistic estimate of the feasibility of wastewater-based detection

2023-04-25 02:20 UTC, jeffkaufman commented on pathogens/hsv_2.py
> +    source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
Instead of a `source`, this should have `inputs=list(stratified_us_pop.values())`

2023-04-25 02:20 UTC, jeffkaufman commented on pathogens/hva.py
> +    coverage_probability=0.95,
These `coverage_probability` additions, here and below, belong in a separate PR

2023-04-25 12:23 UTC, jeffkaufman commented on pathogens/hva.py
> +    coverage_probability=0.95,
I see, you did them in #23 -- the issue is that you should have either (a) waited to merge #23 until after #22 was in (at which point you merge it to `main`) or (b) set up #23 directly as a pull relative to `main` that only included adding `coverage_probability`.

Not worth fixing now, but something to keep in mind for next time you're chaining PRs!

2023-04-27 01:23 UTC, merged