Copenhagen estimates for HIV and HCV. Also edited test.py, as it runs an example test on HIV estimates.
naobservatory/p2ra pull request #222
Opened 2023-07-26 16:12 UTC by simonleandergrimm

Added Copenhagen estimates for HIV and HCV. 

Also edited test.py, as it runs an example test on HIV estimates.

2023-07-26 19:29 UTC, dp-rice requested changes

2023-07-26 19:29 UTC, dp-rice commented on pathogens/hiv.py
> +        * hiv_share_copenhagen
I don't understand this calculation. It looks like you're taking the number of undiagnosed cases in all of Denmark and dividing by the population in all of Denmark to get the prevalence (of undiagnosed cases) in Denmark. Multiplying this by the fraction of cases that are in Copenhagen won't get you the prevalence in Copenhagen without also including the population of Copenhagen in the calculation.

2023-07-26 19:29 UTC, dp-rice commented on pathogens/hiv.py
> +    # (28/108)
Why use the older estimate if newer data is available? 1998 is a long time ago.

2023-07-27 13:47 UTC, simonleandergrimm commented on pathogens/hiv.py
> +        * hiv_share_copenhagen
The population I'm using is the population from Copenhagen, see definition of `copenhagen_population_2022`:
```
copenhagen_population_2022 = Population(
    people=652_221,
    country="Denmark",
    date="2022",
    source="https://kk.statistikbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=KKBEF1"
    # Search variables: Copenhagen in total, Gender in general, Age in total,
    # 2022 Q4
)
```

The order of the calculation is still kind of weird (going from country-wide absolute prevalence directly to Copenhagen prevalence rate, and then scaling down to account for the fact that half of infected people are outside of Copenhagen).

I've changed the PrevalenceAbsolute Python object to make the calculation clearer:

I take the overall, absolute number of undiagnosed HIV positive individuals (denmark_infected_undiagnosed_2022), and scale it down by the share of individuals with HIV in Copenhagen(hiv_share_copenhagen). 

Then, I turn the absolute number of HIV-positive undiagnosed people in Copenhagen (a PrevalenceAbsolute object) into a Prevalence, by incorporating Copenhagen's population.

2023-07-27 13:50 UTC, simonleandergrimm commented on pathogens/hiv.py
> +        * hiv_share_copenhagen
The population I'm using is the population from Copenhagen, see definition of copenhagen_population_2022:

copenhagen_population_2022 = Population(
    people=652_221,
    country="Denmark",
    date="2022",
    source="https://kk.statistikbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=KKBEF1"
    # Search variables: Copenhagen in total, Gender in general, Age in total,
    # 2022 Q4
)
The order of the calculation is still kind of weird (going from country-wide absolute prevalence directly to Copenhagen prevalence rate, and then scaling down to account for the fact that half of infected people are outside of Copenhagen).

I've changed the PrevalenceAbsolute Python object to make the calculation clearer:

I take the overall, absolute number of undiagnosed HIV positive individuals (denmark_infected_undiagnosed_2022), and scale it down by the share of individuals with HIV in Copenhagen(hiv_share_copenhagen).

Then, I turn the absolute number of HIV-positive undiagnosed people in Copenhagen (a PrevalenceAbsolute object) into a Prevalence, by incorporating Copenhagen's population.

2023-07-27 14:04 UTC, simonleandergrimm commented on pathogens/hiv.py
> +    # (28/108)
Good point, I changed it. Also added date from 2017 and 2018.

2023-07-27 14:06 UTC, simonleandergrimm commented
Added multiplication method to PrevalenceAbsolute to make ` copenhagen_2022` HIV calculation more obvious

2023-07-27 14:30 UTC, dp-rice approved these changes
Looks good, thanks!

2023-07-27 14:31 UTC, dp-rice commented
@simonleandergrimm I'm going to merge this so I can go ahead with the fitting

2023-07-27 14:31 UTC, merged