Asher dengue
naobservatory/p2ra pull request #35
Opened 2023-04-25 17:56 UTC by asherps

Updated file

2023-04-25 18:00 UTC, jeffkaufman commented
@simonleandergrimm can you take first pass, and then add me as a reviewer once you think it's ready to go in?

2023-04-26 14:42 UTC, simonleandergrimm commented
@asherps I left initial comments! Overall the doc looks good, you just need to use the objects and methods defined by Jeff.

2023-04-26 14:42 UTC, simonleandergrimm requested changes

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +background = """Dengue virus, a mosquito-borne viral infection primarily transmitted by the Aedes aegypti and Aedes albopictus mosquitoes, present in tropical and subtropical regions. The virus prese
Line length should be shorter. You can use `black --line-length 79 pathogens/dengue.py` to fix this.

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +    taxid=12814,
This is the tax id of RSV

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +    people=39000000,
Please provide a source for the population. census.gov has good data on this.

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +disease_duration = Scalar(
You should use SheddingDuration here, this is a variable just like `PrevalenceAbsolute`.

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +per100k = Scalar(
You don't need to define this. You can get from `PrevalenceAbsolute` to `Prevalence` by using the `to_rate` method, which is part of the `PrevalenceAbsolute` class.

Note that this comment is obsolete, as your `PrevalenceAbsolute` variable should be `IncidenceAbsolute`.

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +    source="https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/TravelAssociatedCasesofDengueVirusinCA.pdf",
This shouldn't be PrevalenceAbsolute, but `IncidenceAbsolute`. You can get from `IncidenceAbsolute` to `Prevalence` by using the `to_prevalence` method.

2023-04-26 14:42 UTC, simonleandergrimm commented on pathogens/dengue.py
> +def estimate_prevalences():
This needs changing once you updated the things I pointed out above!

2023-04-26 16:45 UTC, jeffkaufman commented on pathogens/dengue.py
> +background = """Dengue virus, a mosquito-borne viral infection primarily transmitted by the Aedes aegypti and Aedes albopictus mosquitoes, present in tropical and subtropical regions. The virus prese
You can just do `black .`:

* The `--line-length 79` isn't necessary because `black` will read it from our `[pyproject.toml](https://github.com/naobservatory/p2ra/blob/main/pyproject.toml)` (thanks Dan!).
* Every python file in the repo should be formatted by `black`, and `.` tells it to just do this directory and all children.

In this case, though, you need to fix it manually or with a tool built into your editor: `black` won't rewrap long strings.

2023-04-27 13:38 UTC, simonleandergrimm commented on pathogens/dengue.py
> +    taxid=12637,
This should now be `taxid=TaxID(12637)`. See this discussion: https://twist.com/a/197793/ch/661244/t/4339721/ and pull request #32.

2023-04-27 13:38 UTC, simonleandergrimm commented on pathogens/dengue.py
> +    people=39538245,
nit pick: You can add a date here too (2020-04)

2023-04-27 15:28 UTC, asherps commented on pathogens/dengue.py
> +    people=39538245,
I pushed them! Let me know what you think. The TaxID thing isn't registering on my computer yet; it may be that I need to merge.

2023-04-28 16:36 UTC, simonleandergrimm requested changes

2023-04-28 16:36 UTC, simonleandergrimm commented on pathogens/dengue.py
> +background = """Dengue virus, a mosquito-borne viral infection primarily transmitted
The line break here is >79. Once that is resolved, I'll approve this PR!

2023-05-02 15:01 UTC, simonleandergrimm commented
@jeffkaufman This PR ready for you review.

2023-05-02 19:05 UTC, jeffkaufman approved these changes

2023-05-02 19:05 UTC, jeffkaufman commented on pathogens/dengue.py
> +    people=39538245,
nit: change `39538245` to `39_538_245`

2023-05-02 20:26 UTC, merged