Pull in read count data from the MGS dashboard repo
naobservatory/p2ra pull request #38
Opened 2023-04-25 23:05 UTC by dp-rice

2023-04-25 23:08 UTC, dp-rice commented
@jeffkaufman I'll probably reorganize this code and I still need to write tests, but it would be helpful if you could take a look and see whether it looks like what I'm doing makes sense. One difference from the dashboard is that I am counting reads attributed to non-leaf nodes of the taxonomy. Do you think that's the right thing to do, or should I try to match the dashboard exactly?

2023-04-26 13:17 UTC, jeffkaufman commented on get_mgs_data.py
> +        mgs_dir / "dashboard/metadata_bioprojects.json"
I haven't used pathlib before, but this is neat!  I should probably switch to it.

2023-04-26 13:18 UTC, jeffkaufman commented on get_mgs_data.py
> +    fine_location: str | None = None
I thought earlier you said you preferred `Optional[...]` to `... | None`?

2023-04-26 13:30 UTC, dp-rice commented on get_mgs_data.py
> +    fine_location: str | None = None
You're right! Don't know why I did that.

2023-04-26 14:21 UTC, jeffkaufman commented on get_mgs_data.py
> +def get_subtree(tree: Tree[T], val: T) -> Tree[T] | None:
I'd put this and the other tree operations inside Tree

2023-04-26 14:27 UTC, jeffkaufman commented
> One difference from the dashboard is that I am counting reads attributed to non-leaf nodes of the taxonomy. Do you think that's the right thing to do, or should I try to match the dashboard exactly?

That was a dashboard bug; thanks for catching it!  I've fixed this in 022f461.

I think your code and the dashboard should give the same numbers, but if the dashboard is wrong that's not necessarily a problem with your code ;)

2023-04-26 14:29 UTC, dp-rice commented
I'm working on a version that grabs the json files from github rather than reading them from disk. I'm thinking that this will facilitate testing and also make it simpler to use. Does that seem like a good idea?

2023-04-26 14:30 UTC, jeffkaufman commented
> I'm working on a version that grabs the json files from github rather than reading them from disk. I'm thinking that this will facilitate testing and also make it simpler to use. Does that seem like a good idea?

Whichever feels more comfortable to you!

2023-04-26 18:26 UTC, dp-rice commented
I think this is ready to merge. The next step will be to combine this data with the pathogen data and run the statistics on it.
I'm not super happy with the tests I wrote. They're a combination of fuzzing and a few arbitrary simple examples. I'd appreciate any advice on writing better tests. Also, what do you think of property-based testing (e.g. [hypothesis](https://hypothesis.readthedocs.io/en/latest/)). I like it in principle but the tests take a long time to run.

2023-04-26 18:56 UTC, jeffkaufman requested changes
Looks good!  Only minor issues

2023-04-26 18:56 UTC, jeffkaufman commented on get_mgs_data.py
> +import mgs
`#!/usr/bin/env python3`

2023-04-26 18:56 UTC, jeffkaufman commented on get_mgs_data.py
> +repo = mgs.GitHubRepo(user="naobservatory", repo="mgs-pipeline", branch="main")
Code that actually does something should be downstream from an `if __name__ == "__main__"`

2023-04-26 18:56 UTC, jeffkaufman commented on get_mgs_data.py
> +    if subtree:
nit: I generally prefer `if not subtree: continue` to avoid deep indentation and make it clear there's nothing hiding later, but up to you

2023-04-26 18:56 UTC, jeffkaufman commented on get_mgs_data.py
> +    print(pathogen_name)
Can you include the output of this script in the PR description?  Generally good to do this anytime you're adding something that prints things, as a quick substitute for writing tests.

2023-04-26 18:56 UTC, jeffkaufman commented on mgs.py
> +repo_url = "https://raw.githubusercontent.com/naobservatory/mgs-pipeline/main/"
unused

2023-04-26 18:56 UTC, jeffkaufman commented on mgs.py
> +    url: str = field(init=False)
Since this is only used in one place (the beginning of `get_file`) I think it's not worth the `__post_init__` complexity.  You can just start `get_file` with `file_url = f"https://raw.githubusercontent.com/{self.user}/{self.repo}/{self.branch}/{path}`

2023-04-26 18:56 UTC, jeffkaufman commented on tree.py
> +def tree_from_list(input: list) -> Tree:
I think this would be clearer as a `@staticmethod` on Tree?  So `Tree.from_list(l)` and not `tree_from_list(l)`?

2023-04-26 18:56 UTC, jeffkaufman commented
Also, PR description should say what this PR actually does.

2023-04-26 19:18 UTC, dp-rice commented on tree.py
> +def tree_from_list(input: list) -> Tree:
Good catch

2023-04-26 19:19 UTC, dp-rice commented on mgs.py
> +    url: str = field(init=False)
Good point. I had originally thought we might want do do other stuff with this, but that seems unlikely.

2023-04-26 19:54 UTC, jeffkaufman approved these changes
looks good, only minor comments

(approving now to indicate I don't need to re-review after you fix these unless something surprising comes up)

2023-04-26 19:54 UTC, jeffkaufman commented on get_rothman_virus_counts.py
> +        print("All", sum(virus_counts[s] for s in samples), sep="\t")
nit: I'd indent this (`" All"`)

2023-04-26 19:54 UTC, jeffkaufman commented on get_rothman_virus_counts.py
> +            print(
This too

2023-04-26 19:54 UTC, jeffkaufman commented on test.py
> +
It would be nice to have a test that verifies this matches [0, [1], [2], [3]]

2023-04-26 19:54 UTC, jeffkaufman commented on tree.py
> +    def _helper(self, depth: int) -> str:
`_str_helper`

2023-04-26 20:27 UTC, merged