Added HVA.py | Ready for review by Jeff
naobservatory/p2ra pull request #4
Opened 2023-04-19 21:51 UTC by simonleandergrimm

I now added HVA.py, a script calculating the prevalence of Hepatitis A virus for Seattle in 2017 and 2018, and for the US in 2018. 

Let me know what you think, I'd be particularly keen to make the code more efficient (for instance, I'm referring to the `prevalence_est` dictionary (prevalence estimators) 7 times in the final calculation).

2023-04-20 02:14 UTC, jeffkaufman requested changes

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://www.cdc.gov/hepatitis/statistics/2018surveillance/index.htm",
Is there a more specific URL?  I don't see 12474 on that page

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://www.google.com/search?q=us+population+2018&oq=us+population+2018&aqs=chrome.0.69i59j0i512j0i22i30l6j0i390i650l2.5937j1j7&sourceid=chrome&ie=UTF-8",
The `&oq=us+population+2018&aqs=chrome.0.69i59j0i512j0i22i30l6j0i390i650l2.5937j1j7&sourceid=chrome&ie=UTF-8` isn't doing anything

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +    "us_population_2018": PrevalenceEstimator(
Doesn't have to be fixed now, but at some point we'll want a way to pull commonly referenced numbers like the US population out into something shared

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://www.google.com/search?q=us+population+2018&oq=us+population+2018&aqs=chrome.0.69i59j0i512j0i22i30l6j0i390i650l2.5937j1j7&sourceid=chrome&ie=UTF-8",
I guess citing "google" is ok for numbers this basic, though I'd feel slightly better about citing the actual primary source, which in this case is the census

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        value=14,
The source has `1-3 weeks` -- I think we should include that range here, and have the code that works with the variable take the midpoint if it wants

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://doh.wa.gov/sites/default/files/2023-01/420-004-CDAnnualReport2021.pdf?uid=642c448518316#page=28",
It looks like you're interpreting this as "infections / population", but isn't it actually "confirmed cases / population"?  In which case don't we need to adjust for underreporting?

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +        value=0.5,
We should also copy over the absolute number of cases, since that's useful for estimating the error

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +    "us_prevalence_2018": calculate_prevalence_from_absolute_incidence(
Instead of doing `var.value` everywhere, pass the `PrevalenceEstimator` to the function and have it do the work.

Additionally, `calculate_prevalence_from_incidence_rate` can verify that the `value_type` it's been given is correct.

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +    "us_prevalence_2018": calculate_prevalence_from_absolute_incidence(
Possibly we should use the type system more and every distinct `value_type` should be a different class?  Then we can use `mypy` for static typechecking?

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +    return prevalence
These two functions should be somewhere more general where they can be shared, though you don't have to fix this in this PR.

2023-04-20 02:14 UTC, jeffkaufman commented on pathogens/hva.py
> +    incidence_rate = (absolute_incidence / population) * 100000
Not good to have "10000" here without anything connecting it to `unit="cases_per_100k"`.

2023-04-20 13:43 UTC, jeffkaufman commented
Separately: you don't need to put "ready for review by X" in the title.  You can use the Reviewers system to specifically request a review from someone, and if you don't want anyone looking at your PR you can [convert it to a draft](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/) (see the upper right hand corner of this page for what that link looks like)

2023-04-20 14:34 UTC, jeffkaufman commented on pathogens/hva.py
> +    na_type=NAType.RNA.value,
See https://github.com/naobservatory/p2ra/pull/7 for where I fixed this for `hsv_1.py`

2023-04-20 16:03 UTC, jeffkaufman commented on pathogens/hva.py
> +    return prevalence
Done in https://github.com/naobservatory/p2ra/pull/10

2023-04-20 16:03 UTC, jeffkaufman commented on pathogens/hva.py
> +    "us_prevalence_2018": calculate_prevalence_from_absolute_incidence(
Done in https://github.com/naobservatory/p2ra/pull/10

2023-04-20 18:33 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://www.cdc.gov/hepatitis/statistics/2018surveillance/index.htm",
Also should include confidence interval

2023-04-20 19:11 UTC, simonleandergrimm commented on pathogens/hva.py
> +        source="https://www.cdc.gov/hepatitis/statistics/2018surveillance/index.htm",
https://www.cdc.gov/hepatitis/statistics/2018surveillance/HepA.htm

2023-04-20 19:23 UTC, simonleandergrimm commented on pathogens/hva.py
> +        source="https://www.google.com/search?q=us+population+2018&oq=us+population+2018&aqs=chrome.0.69i59j0i512j0i22i30l6j0i390i650l2.5937j1j7&sourceid=chrome&ie=UTF-8",
(Not actually outdated, I still need to change the source to the census.

2023-04-21 13:51 UTC, jeffkaufman requested changes

2023-04-21 13:51 UTC, jeffkaufman commented on pathogens/hva.py
> +it's mostly spread by individual contact. There is little seasonal variance in Hepatitis A incidence (https://www.cdc.gov/vaccines/pubs/pinkbook/hepa.html). Viral shedding persists for 1 to 3 weeks."
This is 112 columns though?

2023-04-21 13:51 UTC, jeffkaufman commented on pathogens/hva.py
> +        source="https://doh.wa.gov/sites/default/files/2023-01/420-004-CDAnnualReport2021.pdf?uid=642c448518316#page=28",
I don't see where you've adjusted for underreporting?

I expect when you do you'll want to use `Scalar` introduced in #12

2023-04-21 13:51 UTC, jeffkaufman commented on pathogens/hva.py
> +        value=0.5,
I still don't see this?

2023-04-21 14:42 UTC, simonleandergrimm commented on pathogens/hva.py
> +it's mostly spread by individual contact. There is little seasonal variance in Hepatitis A incidence (https://www.cdc.gov/vaccines/pubs/pinkbook/hepa.html). Viral shedding persists for 1 to 3 weeks."
Fixed

2023-04-21 14:44 UTC, simonleandergrimm commented on pathogens/hva.py
> +        value=0.5,
I added the variables king_county_absolute_2017 and king_county_absolute_2018.

2023-04-21 17:15 UTC, jeffkaufman commented on pathogens/hva.py
> +it's mostly spread by individual contact. There is little seasonal variance in Hepatitis A incidence (https://www.cdc.gov/vaccines/pubs/pinkbook/hepa.html). Viral shedding persists for 1 to 3 weeks."
Still not fixed

2023-04-21 19:03 UTC, jeffkaufman approved these changes
Looks good!  Feel free to go ahead and merge after handling the two small comments below.

2023-04-21 19:03 UTC, jeffkaufman commented on pathogens/hva.py
> +    end_date="2018-12-31",
This (and all below) can now just be `date="YYYY"`.  So `date="2018"`.

2023-04-21 19:25 UTC, jeffkaufman commented on pathogens/hva.py
> +    date="2018",
Just noticed that this won't work until #15 goes in, sorry!  But #15 should be going in as soon as you finish your review...

2023-04-21 19:34 UTC, merged