Asher ebv
naobservatory/p2ra pull request #49
Opened 2023-04-27 20:44 UTC by asherps

Updated EBV doc with a latent prevalence estimate

2023-04-28 16:34 UTC, simonleandergrimm commented
> Updated EBV doc with a latent prevalence estimate

@asherps Please assign the Review of Pull Requests to me upon submission; I don't get a notification otherwise.

2023-05-03 19:57 UTC, simonleandergrimm requested changes
Good first draft, you adopted a lot of the changes we suggested in other docs. Missing from this doc is an estimate of yearly mononucleosis cases across the US, which would represent the active estimate for EBV. Please add that.

2023-05-03 19:57 UTC, simonleandergrimm commented on .vscode/settings.json
Ditto

2023-05-03 19:57 UTC, simonleandergrimm commented on Titanic.ipynb
Ditto

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +
Fix indent.

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    infections_per_100k=0.853 * 100_000,
Please add this part of the methods here, as a comment:
"We conducted a sero-epidemiological survey using serum samples from 2325 individuals between 0 and 25 years old to assess prevalence of detectable anti-EBV antibodies."

In general, if there are small parts of a study that seem very relevant, put them in the doc

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +UK_study = Prevalence(
Give a more descriptive name here, i.e., uk_seroprevalence_0_to_25yo

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +# in the estimate, but rather to confirm that the estimate is reasonable
I wouldn't use this estimate if we don't have access to its source. You can't know this but the journal 'Viruses' has pretty dodgy papers.

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    infections_per_100k=0.665 * 100_000,
There is a CI here you can use: 66.5% (95% CI 64.3%-68.7%.)

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    infections_per_100k=0.665 * 100_000,
Also a number of participants

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +# this study looks only at children. It is also not used in the estimate,
Put this comment under `US_children_study = Prevalence(`. You don't need to mention children, as that is mentioned in the variable name.

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +US_children_study = Prevalence(
Call this prevalence object `nhanes_children_estimate`

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/EBV.py
> +
I would add a further estimate, representing only the 18-19yo age band in this table: https://academic.oup.com/jid/article/208/8/1286/2192838#:~:text=Table%201.Demographic%20Factors%20Associated%20With%20Epstein%E2%80%93Barr%20Virus%20(EBV)%20Antibody%20(Ab)%20Prevalence%2C%20by%20Race/Ethnicity%E2%80%94National%20Health%20and%20Nutrition%20Examination%20Survey%20Cycles%202003%E2%80%932004%2C%202005%E2%80%932006%2C%202007%E2%80%932008%2C%20and%202009%E2%80%932010

Given that EBV stays latent, we can use this number as a rough proxy for the remaining US population (though should clearly flag this estimate as only pertaining to 18-19yo)

2023-05-03 19:57 UTC, simonleandergrimm commented on pathogens/dengue.py
This doc shouldn't be here.

2023-05-03 20:57 UTC, asherps commented on pathogens/EBV.py
> +# in the estimate, but rather to confirm that the estimate is reasonable
Is it fine to keep there but not use, or should I just delete it? Probably just delete?

2023-05-04 17:16 UTC, simonleandergrimm reviewed
This looks good and is nearly ready for review by Jeff. Before we do that, please adapt the suggested changes, and change the pull request to into main, it is currently a bit confusing that 6 changed different pathogen docs are listed under pathogens, while we only want to review EBV.py

2023-05-04 17:16 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    date="2009",
start and end_date should look the same as in the above prevalence

2023-05-04 17:16 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    # but helps confirm that the estimate is reasonable
This comment is outdated

2023-05-04 17:21 UTC, simonleandergrimm requested changes

2023-05-04 17:21 UTC, simonleandergrimm commented on pathogens/EBV.py
> +from pathogen_properties import *
Missed to submit comments as "Request Changes", instead I just commented.

2023-05-04 18:02 UTC, asherps commented on .DS_Store
I couldn't find it anywhere, sorry

2023-05-04 18:31 UTC, simonleandergrimm requested changes

2023-05-04 18:31 UTC, simonleandergrimm commented on .DS_Store
Before my review, please change the target branch to `main` instead of `asher_latent`.

2023-05-04 18:35 UTC, simonleandergrimm commented
Nice job! After fixing the target branch of this pull request (and thus removing a lot of files from the PR), I'm happy to have this reviewed by Jeff.

2023-05-04 18:37 UTC, simonleandergrimm requested changes

2023-05-04 18:37 UTC, simonleandergrimm commented on pathogen_properties.py
>  import datetime
As mentioned, looking good. Just remove unnecessary files in the PR (by changing target branch), then assign it back to me.

2023-05-04 19:08 UTC, jeffkaufman commented
The diff is messed up, I think maybe because of manually pulling things from `main`?  I think you can fix it with:

```
git checkout main
git pull
git checkout asher_EBV
git merge main
```

Then you can resolve conflicts, commit, and `git push`.  After that reassign to me and I'll review.

2023-05-09 20:13 UTC, simonleandergrimm requested changes

2023-05-09 20:13 UTC, simonleandergrimm commented on pathogens/EBV.py
> +        + nhanes_children_estimate.__mul__(US_child_proportion)
Correction, after looking into the methods we can do this more efficiently. The following code should work, using the built in `.__add__` method

`us_seroprevalence_2003_2010 = (
    nhanes_18_19_yo_estimate.__mul__(US_adult_proportion)
).__add__(nhanes_children_estimate.__mul__(US_child_proportion))`

2023-05-09 21:24 UTC, simonleandergrimm requested changes
Added one comment on inserting a required TODO for myself.

2023-05-09 21:24 UTC, simonleandergrimm commented on pathogens/EBV.py
> +
Add this Todo:
`TODO: Simon will look into incidence of mononucleosis in the US. There is
 also the question of mono being a proxy for EBV infection, or activation.`

2023-05-09 21:24 UTC, simonleandergrimm requested changes
Added one comment on inserting a required TODO for myself.

2023-05-10 18:29 UTC, simonleandergrimm approved these changes

2023-05-10 19:17 UTC, jeffkaufman requested changes

2023-05-10 19:17 UTC, jeffkaufman commented on .gitignore
> +# Settings.json
Either explain what `settings.json` is or drop the comment

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    active=Active.LATENT,
include `number_of_participants=2325`

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +nhanes_children_estimate = Prevalence(
"children" is ambiguous; how about `nhanes_age_8_19_estimate`?

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +US_child_proportion = Scalar(
This should say what ages it means

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +US_adult_proportion = Scalar(
This too

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +).__add__(nhanes_children_estimate.__mul__(US_child_proportion))
`nhanes_18_19_yo_estimate * US_adult_proportion + nhanes_children_estimate * US_child_proportion`

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    return [us_seroprevalence_2003_2010]
In a follow-up PR, what would you think of doing an estimate for Denmark in 2015-2016?  Because that's where our good DNA data is from.

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +# anti-EBV antibodies."
Why not include this estimate in the output?

2023-05-10 19:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +# this estimate uses children 18-19 as a proxy for the adult population
That's not ideal; does nhanes really not give seroprevalence for older people?

2023-05-10 19:17 UTC, jeffkaufman requested changes
Looks good, but still some issues

2023-05-10 19:45 UTC, simonleandergrimm commented
> Looks good, but still some issues

@jeffkaufman , This should be assigned to Asher, or no?

2023-05-10 20:49 UTC, asherps commented on pathogens/EBV.py
> +# anti-EBV antibodies."
It's just for ages 0-25, so it's probably not a great number to use as an overall prevalence without modification?

2023-05-11 15:07 UTC, asherps commented on pathogens/EBV.py
> +# this estimate uses children 18-19 as a proxy for the adult population
Not that I can find

2023-05-11 16:22 UTC, jeffkaufman requested changes
Looks good, except a small number of things are marked fixed that aren't fixed?

2023-05-11 16:22 UTC, jeffkaufman commented on .gitignore
> +# Settings.json
Doesn't look fixed?

2023-05-11 16:22 UTC, jeffkaufman commented on pathogens/EBV.py
> +# anti-EBV antibodies."
I don't know; your other estimate assumes everyone 18+ has the infection rate of 18-year-olds, so it's not much worse than that?

2023-05-11 16:22 UTC, jeffkaufman commented on pathogens/EBV.py
> +    infections_per_100k=0.853 * 100_000,
I don't see this comment added?

2023-05-11 16:22 UTC, jeffkaufman commented on pathogens/EBV.py
> +# this estimate uses children 18-19 as a proxy for the adult population
Ok, this doesn't matter very much, because the rate is already so high at age 18.

2023-05-11 18:27 UTC, asherps commented
> Looks good, except a small number of things are marked fixed that aren't fixed?

As far as I can tell, everything was fixed except for the comment on gitignore which was back for some reason? I'm going to push again; everything looks fine on my local branch.

2023-05-11 19:52 UTC, jeffkaufman requested changes
looks good aside from the one thing that's still not done

2023-05-11 19:52 UTC, jeffkaufman commented on pathogens/EBV.py
> +    infections_per_100k=0.853 * 100_000,
I still don't see `We conducted a sero-epidemiological survey using serum samples from 2325 individuals between 0 and 25 years old to assess prevalence of detectable anti-EBV antibodies.`

Please don't resolve this comment unless you do see the text in the github diff.

2023-05-16 19:30 UTC, asherps commented on pathogens/EBV.py
> +    infections_per_100k=0.853 * 100_000,
I do see the comment in the Github diff on lines 21-23. Do you not see it there? Should it be inside the prevalence object or something?

2023-05-23 15:42 UTC, simonleandergrimm commented
@jeffkaufman Looks good to me, Asher also added the comment that was still required 
```
We conducted a sero-epidemiological survey using serum samples from 2325 individuals between 0 and 25 years old to assess prevalence of detectable anti-EBV antibodies.
```

After your OK @asherps  can merge this.

2023-05-23 18:35 UTC, jeffkaufman requested changes
Almost ready!

2023-05-23 18:35 UTC, jeffkaufman commented on pathogens/EBV.py
> +) + nhanes_age_8_19_estimate * (under_18_proportion_US)
WeightedAverageByPopulation

2023-05-24 00:43 UTC, simonleandergrimm commented
@asherps This is currently failing checks, I'll assign it back to you.

2023-05-24 19:11 UTC, asherps commented
> @asherps This is currently failing checks, I'll assign it back to you.

It should stop failing checks as soon as EBV Denmark is merged in (this adds weightedAverageByPopulation). It was passing checks before I switched to using weightedAverageByPopulation. For now, I suggest we just wait for the merge unless you're in a a rush to merge it w main.

2023-05-30 20:22 UTC, simonleandergrimm commented
Superseded by #123

2023-05-30 20:22 UTC, closed without merging