Asher vzv
naobservatory/p2ra pull request #65
Opened 2023-05-02 18:38 UTC by asherps

Completed estimates for latent VZV prevalence, active chickenpox prevalence, and active shingles prevalence. For the latent VZV estimate, I had to be loose with the formatting to make the estimate work, using Scalars a lot instead of more specific values.

2023-05-02 19:16 UTC, simonleandergrimm requested changes

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    scalar=4000000,
Structure long numbers with underscores: 4_000_000

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    people=335000000,
Would add a more formal source here, e.g. population projection for 2023 (appreciate that no Census data for 2023 seems to exist on data.census.gov)

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    people=335000000,
Also include seperators _

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    infections_per_100k=annual_new_VZV_infections.scalar
I think this should be doable with the given toolkit from Jeff. Potentially it'd be good to have pathogen_properties.py open next to the pathogen doc, that is what I do to spot the appropriate functions.

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    tag="US-2023",
This is from 2020. I would look into their references to get a better handle on the exact date of the source

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +shingles_duration = SheddingDuration(
Add the CI in the document: three to five weeks.

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    tag="US-2023",
https://www.cdc.gov/shingles/hcp/clinical-overview.html#:~:text=Last%20Reviewed%3A,Chickenpox%20Q%26As

2023-05-02 19:16 UTC, simonleandergrimm commented on pathogens/vzv.py
> +    days=12,
Add CI: 10 to 14 days

2023-05-02 19:24 UTC, jeffkaufman requested changes
good start!

2023-05-02 19:24 UTC, jeffkaufman commented on .vscode/settings.json
> +}
This should not be in this PR

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    scalar=4000000,
4_000_000

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    source="https://www.childrenshospital.org/conditions/chickenpox#:~:text=More%20than%2095%20percent%20of%20American%20adults%20have%20had%20chickenpox%20and%20about%204%2C000%2C000%20people%20get%
This isn't a great source, and it's uncited.

I also think it's probably wrong? https://www.cdc.gov/chickenpox/vaccination-program-impact.html has "Before the [vaccination] program began, chickenpox used to be very common in the country. Each year in the early 90s, there were more than 4 million cases of chickenpox" ... "Now, chickenpox is rare in the United States, with fewer than 150,000 cases"

Maybe you can get the actual info from https://www.cdc.gov/chickenpox/health-departments/conducting-surveillance.html ?

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    people=335000000,
335_000_000

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    infections_per_100k=annual_new_VZV_infections.scalar
Don't do this sort of calculation manually.  Start with an `AboluteIncidence`.

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +shingles_annual_infections = IncidenceAbsolute(
Since the source has a relative incidence, probably better to use that?  Then we don't have to worry about whether we're using the same year's population.

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    source="https://www.childrenshospital.org/conditions/chickenpox#:~:text=More%20than%2095%20percent%20of%20American%20adults%20have%20had%20chickenpox%20and%20about%204%2C000%2C000%20people%20get%
As above, this is wrong

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    source="https://www.nia.nih.gov/health/shingles#:~:text=Most%20cases%20of%20shingles%20last%20three%20to%20five%20weeks.",
Let's record the range: `confidence_interval=[3,5]`

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    source="https://my.clevelandclinic.org/health/diseases/4017-chickenpox#:~:text=Chickenpox%20usually%20goes%20away%20after%2010%20to%2014%20days.",
here too: 10-14

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +)
ditto

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    .infections_per_100k,
ditto

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +        shingles_active_prevalence,
I don't think this quite makes sense: active prevalence is chickenpox_active_prevalence + shingles_active_prevalence, no? [1]

The idea is, the amount of the virus we see in wastewater from active infections should be based on people actively shedding for both categories of infections.

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    + prevalence_from_postvaccine_cases.infections_per_100k,
Don't pull infections_per_100k out of a `Prevalence` to make a new `Prevalence` -- that's very error prone.  Always use the built-in methods.  If you need to do something that can't be done with the built-ins consider adding one (in this case I think a new method would be very good) or post in `#p2ra-noisy` for guidance.

2023-05-02 19:24 UTC, jeffkaufman commented on pathogens/vzv.py
> +    + prevalence_from_postvaccine_cases.infections_per_100k,
The method could look like:

```
def __add__(self: "Prevalence", other: "Prevalence") -> "Prevalence":
    assert self.active == other.active
    return Prevalence(
       infections_per_100k=self.infections_per_100k + other.infections_per_100k,
       inputs=[self, other],
       active=self.active,
    )
```

2023-05-02 19:30 UTC, jeffkaufman commented on pathogens/vzv.py
> +    + prevalence_from_postvaccine_cases.infections_per_100k,
Add go put in `__add__` now.

2023-05-11 18:56 UTC, closed without merging

2023-05-11 18:57 UTC, simonleandergrimm commented
I will review this pull request as soon as we refocus on vzv, but I don't want it to be in the PR queue up until then.