Asher rhinovirus
naobservatory/p2ra pull request #66
Opened 2023-05-02 19:20 UTC by asherps

Finished first draft of rhinovirus estimate

2023-05-04 15:10 UTC, simonleandergrimm requested changes

2023-05-04 15:10 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    source="https://www.cdc.gov/ncird/rhinoviruses-common-cold.html",
You can add these prevalences using the new add method.

2023-05-04 15:13 UTC, simonleandergrimm requested changes
@asherps This is good! As mentioned in our brief check-in, you incorporated a lot of the feedback Jeff and I gave in previous PRs. 

Please incorporate (or push back on) the suggested changes. Also **please create a US-wide estimate**, not only an LA specific one.

2023-05-04 17:36 UTC, asherps commented on pathogens/rhinovirus.py
> +LA_county_child_proportion = Scalar(
I tried changing the doc with this edit and it felt more complicated than keeping it as a scalar. Idk, we could talk about it next week.

2023-05-04 19:30 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    taxid=TaxID(147711, 147712, 463676),
Now that #78 is in you can merge `main` and this will work, but the right way to phrase it is:

    taxids=frozenset([TaxID(147711), TaxID(147712), TaxID(463676)]),

2023-05-04 20:00 UTC, simonleandergrimm requested changes
We can discuss the scalar vs non-scalar thing on Tuesday! I left a couple of other minor comments, everything else looks good. Thanks for the hard work!

2023-05-05 19:43 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +LA_county_adult_proportion = Scalar(
I would still make this a population, but let's discuss more on Tues!

2023-05-05 19:51 UTC, simonleandergrimm commented
> We can discuss the scalar vs non-scalar thing on Tuesday! I left a couple of other minor comments, everything else looks good. Thanks for the hard work!

This is another good paper worth looking into: https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(03)12162-9/fulltext

2023-05-09 19:42 UTC, simonleandergrimm requested changes
Looks good! Thanks for finding the source on the pandemic_decrease scalar, I added a note on that accordingly, looking at data from winter 2020. 

I also did some more thinking regarding the Tecumseh study (the one on the average number of cold/rhinovirus infections). I suggested a different but straightforward approach to estimating mean number of cold infections, the one I suggested before is not so good.

2023-05-09 19:42 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +public-health-data#:~:text=December%202022%20%C2%A0(ZIP%20file%2C%203.7%20MB
This is a cool source! You are currently linking to the wrong report, see here for the actual link: https://www.rcgp.org.uk/getmedia/e564cc01-bc66-4165-aba5-c762b693f50d/2020-December.zip

Graph:

![image](https://github.com/naobservatory/p2ra/assets/58591538/647ccaaf-74ab-43d0-b7e9-972cc79a6c8d)

2023-05-09 19:42 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +public-health-data#:~:text=December%202022%20%C2%A0(ZIP%20file%2C%203.7%20MB
And I would anchor more around the week of 44 to 53, which, when compared to the 5yr Avg, looks more like a 6x difference (using the National number [red line]).

2023-05-09 19:42 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    scalar=0.1,
Switch to 0.2, based on linked report and data for winter.

2023-05-09 19:42 UTC, simonleandergrimm requested changes
Looks good! Thanks for finding the source on the pandemic_decrease scalar, I added a note on that accordingly, looking at data from winter 2020. 

I also did some more thinking regarding the Tecumseh study (the one on the average number of cold/rhinovirus infections). I suggested a different but straightforward approach to estimating mean number of cold infections, the one I suggested before is not so good.

2023-05-10 18:46 UTC, simonleandergrimm requested changes

2023-05-10 18:46 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    # The 5-year avg at this time is in blue, and the national avg in red below
Add a comment, saying that this pandemic_decrease_factor only applies to the estimate for LA, and is based on UK data.

2023-05-10 18:46 UTC, simonleandergrimm requested changes
Minor review; please leave the indicated comment at `pandemic_decrease_factor`

2023-05-10 18:46 UTC, simonleandergrimm requested changes
Minor review; please leave the indicated comment at `pandemic_decrease_factor`

2023-05-11 14:52 UTC, simonleandergrimm requested changes

2023-05-11 14:52 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    # should be significantly higher. I'm going to take 0.6 as a guess.
So do you think the incidence being lower means measures in LA were stronger, thus leading to greater suppression of Rhinovirus?

If that is so, shouldn't the decrease factor be smaller, to cause a greater decrease in Rhinovirus numbers?

2023-05-11 16:00 UTC, simonleandergrimm approved these changes

2023-05-12 13:17 UTC, jeffkaufman requested changes

2023-05-12 13:17 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
I like this study, for when it was written, but it's really very old.  Is there nothing more recent?

We shouldn't put too much weight on this being from the US: I'd expect 2020s UK rates, say, to be more similar to 2020s CA rates than to 1976-1981 Tecumseh Michigan rates.  In this time there have been big changes to how people live, Michigan and CA aren't that similar, Rhinoviruses have had a lot of time to evolve, etc.

2023-05-12 13:17 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
I haven't looked into this study, but if they're able to tell that there's a decrease can we also get absolute numbers?  Can we get how they varied over time?

Are there other places where we can get these numbers?  If several non-LA places agree on the numbers then I'd be happier treating them as an approximation of LA numbers.

2023-05-12 13:17 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +        total_prevalence.__mul__(pandemic_decrease_factor),
`total_prevalence * pandemic_decrease_factor`

2023-05-16 19:08 UTC, asherps commented
I think this new second estimate is now in decent shape, although there is still a fair bit of uncertainty in the pandemic_decrease_factor and annual_number_of_colds. Still, it would be pretty surprising to me if this estimate were off by more than a factor of 3 or so. Also, my guess is that the very old study used in the first of the two estimates is just pretty inaccurate for the fall, and we should just get rid of this estimate? It finds that 34% of colds were caused by rhinovirus, which does not line up at all with the 4 other estimates I found for this parameter during fall specifically. It's also very possible that the number of rhinoviruses per year has changed significantly in the last 50 years.

2023-05-17 13:55 UTC, jeffkaufman requested changes
I didn't review the whole thing; after pulling each bit of data you're combining into a separate variable I can review again?

Also happy to talk in person if any of this is unclear.

2023-05-17 13:55 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
This should be an `IncidenceRate`, since that's what the source is estimating:

```
annual_rhinovirus_infections_under_19 = IncidenceRate(
    # The weighted average annual number of respiratory illnesses among
    # 0-19-year-olds is in parentheses, aggregating the mean of 0-4 and 5-19
    # year olds from table 1 of the source
    # rhinovirus_share_of_cold = 0.34
    annual_infections_per_100k=((539 * 4.9 + 1541 * 2.8) / (539 + 1541))
    * 0.34
    * 100_000
    date="2020",
    tag="under 18",
    source="doi.org/10.1017/S0950268800050779#?page=6",
)
```

This also means you can set the date to when the estimate is from

2023-05-17 13:55 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    source="doi.org/10.1017/S0950268800050779#?page=6",
nit: `https://doi.org/...`

2023-05-17 13:55 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +annual_rhinovirus_infections_under_19 = IncidenceAbsolute(
Let's more closely represent the data we're pulling from the table. This would look like:

```
cold_0_4 = IncidenceRate(
   annual_infections_per_100k = 4.9 * 1e6,
   # Table 1, (c)
   source="https://doi.org/10.1017/S0950268800050779",
   ...
)

cold_5_19 = IncidenceRate(
   annual_infections_per_100k = 2.8 * 1e6,
   # Table 1, (c)
   source="https://doi.org/10.1017/S0950268800050779",
   ...
)

cold_20_39 = IncidenceRate(
   annual_infections_per_100k = 2.2 * 1e6,
   # Table 1, (c)
   source="https://doi.org/10.1017/S0950268800050779",
   ...
)

cold_40_plus = IncidenceRate(
   annual_infections_per_100k = 1.6 * 1e6,
   # Table 1, (c)
   source="https://doi.org/10.1017/S0950268800050779",
   ...
)
```

Except Table 2 has Rhinoviruses specifically, so I think we should use that instead:

```
rhinovirus_0_4 = IncidenceRate(
   annual_infections_per_100k = 113.2 * 100,
   # Table 2, Rhinoviruses.
   # "Annual isolation rates of respiratory viruses, Tecumseh Michigan,
   # USA, 1976-81. Actual rates per 1000 person year"
   source="https://doi.org/10.1017/S0950268800050779",
   date_start="1976",
   date_end="1981",
   country="United States",
   state="Michigan",
   county="Lenawee County",
)
rhinovirus_5_19 = IncidenceRate(
   annual_infections_per_100k = 25.3 * 100,
   # Table 2, Rhinoviruses
   # "Annual isolation rates of respiratory viruses, Tecumseh Michigan,
   # USA, 1976-81. Actual rates per 1000 person year"
   source="https://doi.org/10.1017/S0950268800050779",
   date_start="1976",
   date_end="1981",
   country="United States",
   state="Michigan",
   county="Lenawee County",
)
rhinovirus_20_39 = IncidenceRate(
   annual_infections_per_100k = 38.7 * 100,
   # Table 2, Rhinoviruses
   # "Annual isolation rates of respiratory viruses, Tecumseh Michigan,
   # USA, 1976-81. Actual rates per 1000 person year"
   source="https://doi.org/10.1017/S0950268800050779",
   date_start="1976",
   date_end="1981",
   country="United States",
   state="Michigan",
   county="Lenawee County",
)
rhinovirus_40_plus = IncidenceRate(
   annual_infections_per_100k = 9.7 * 100,
   # Table 2, Rhinoviruses
   # "Annual isolation rates of respiratory viruses, Tecumseh Michigan,
   # USA, 1976-81. Actual rates per 1000 person year"
   source="https://doi.org/10.1017/S0950268800050779",
   date_start="1976",
   date_end="1981",
   country="United States",
   state="Michigan",
   county="Lenawee County",
)
```

Then we can make an estimate for LA County in general:

```
la_county_0_4 = Population(
  people=285_140 + 273_131,
  date="2020"
  country="United States",
  state="California",
  county="Los Angeles County",
  source="http://proximityone.com/chartgraphics/pp06037_2020_001.htm"
)
la_county_5_19 = Population(
  people=(306_835 + 291_053) + (320_666 + 303_381) + (317_657 + 306_849),
  date="2020"
  country="United States",
  state="California",
  county="Los Angeles County",
  source="http://proximityone.com/chartgraphics/pp06037_2020_001.htm"
)
la_county_20_39 = Population(
  people=(330_183 + 327_625) + (406_008 + 399_410) + (413_566 + 394_103) + (370_948 + 355_002),
  date="2020"
  country="United States",
  state="California",
  county="Los Angeles County",
  source="http://proximityone.com/chartgraphics/pp06037_2020_001.htm"
)
la_county = Population(
  people=4_965_022 + 5_048_987,
  date="2020"
  country="United States",
  state="California",
  county="Los Angeles County",
  source="http://proximityone.com/chartgraphics/pp06037_2020_001.htm"
)

la_county_40_plus = la_county - la_county_0_4 - la_county_5_19 - la_county_20_39

rhinovirus_la_county = IncidenceRate.weightedAverageByPopulation(
   (rhinovirus_0_4, la_county_0_4),
   (rhinovirus_5_19, la_county_5_19),
   (rhinovirus_20_39, la_county_20_39),
   (rhinovirus_40_plus, la_county_40_plus),
)
```

Note that this would requiring adding `IncidenceRate.weightedAverageByPopulation` and `Population.__sub__`, which shouldn't be too hard?

2023-05-17 13:55 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    + 6 * la_county_under_18_population.people,
Separate variables for 3.75, 6, and 1.5 so we can track provenance

2023-05-18 13:21 UTC, jeffkaufman requested changes

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    county="Los Angeles County",
Don't include state and county: the estimate isn't for somewhere specific, beyond just the US

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +average_colds_per_year_adults = Scalar(
This is an `IncidenceRate`, not a `Scalar`

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
Do the calculation outside the variable definition:

```
colds_la_county = IncidenceRate.weightedAverageByPopulation(
   (average_colds_per_year_children, la_county_under_18_population),
   (average_colds_per_year_adults, la_county_adult_population))

colds_fall_disproportionality = Scalar(scalar=1.5, ...)

fall_colds_la_county = colds_la_county * colds_fall_disproportionality
```

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
This 0.82 (Fall 1994 in VA) is the same 0.82 as in your `fall_proportion_of_colds_caused_by_rhinovirus_estimate_2`, so right now you're double counting.  I think we can just use `fall_proportion_of_colds_caused_by_rhinovirus_estimate_2`?

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
which means we don't need this

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +)
This looks like another potential source for rhinovirus incidence.  Could you add a comment saying so, in case we later want to come back and incorporate?

2023-05-18 13:21 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    # From this graph, the UK's decrease factor was around 0.2.
We should have one Variable for 0.2, citing the UK data.  Then going from there to 0.4 should be a separate calculation on Variables.

2023-05-18 13:48 UTC, jeffkaufman commented on pathogen_properties.py
> +
Also, the `dataclasses.replace` method needs to update `inputs`

2023-05-18 17:35 UTC, jeffkaufman requested changes
really close!

2023-05-18 17:35 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +colds_fall_disproportionality = Scalar(scalar=1.5)
This needs a source, or at least an explanation

2023-05-18 17:35 UTC, jeffkaufman commented on pathogens/rhinovirus.py
> +    date="2020",
Since this is an estimate for LA, include `country`, `state`, and `county`

2023-05-23 18:06 UTC, asherps commented on pathogens/rhinovirus.py
> +)
The absolute numbers are pretty awful, probably because they represent positive tests for rhinovirus. Hopefully, the year-to-year ratio is still somewhat accurate. I think we ideally don't have to use these numbers at all, but they might have some small significance. I'm looking for other sources right now.

2023-05-23 20:28 UTC, asherps commented on pathogens/rhinovirus.py
> +)
Update: this study is gone and has been replaced with better ones

2023-05-23 23:09 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    # This source finds rhinovirus did not decrease during the pandmeic in
typo "pandmeic"

2023-05-23 23:10 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +# This study finds the hRV actually increased in Australia: https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2020.25.47.2001847#:~:text=In%20contrast%2C%20rhinovirus%20detections%20were%
Typo `findes the hRV`

2023-05-24 00:38 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +# it makes sense to increase the yearround number by some reasonable factor
year-round

2023-05-24 00:42 UTC, simonleandergrimm requested changes
Very close! Left some comments based on discussions we had today. Please reassign to me after getting back to my comments.

2023-05-24 00:42 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +# Assuming people get no colds in the summer and an equal amount of colds
Do you know if colds do not happen in summer?

2023-05-24 00:42 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +finland_china_japan_australia_canada_pandemic_decrease_factor = Scalar(
As discussed, if this scalar is 1, and doesn't change the final estimate, you don't need it. I would instead leave a more structured comment, saying up front that there is no clear trend on whether Rhinovirus prevalence increased or decreased during the pandemic. Afterward you can point to the most significant papers you found.

2023-05-25 14:53 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +# Assuming people get no colds in the summer and an equal amount of colds
Yeah I would drop this for now. Thanks for looking into this!

2023-05-25 14:59 UTC, simonleandergrimm requested changes

2023-05-25 14:59 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +# FWIW, this study claims that Covid Incidence has a significant positive
Do you think this information is relevant for your later estimates? If so leave it, if not drop it.

2023-05-25 14:59 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +rhinovirus_0_4 = IncidenceRate(
As a final thing you can do here: Put the incidences and populations below into separate dictionaries to increase clarity. Also find a way to make the variable definition more efficient, currently you are repeating a lot of information, e.g. this:
```
    # Table 2, Rhinoviruses.
    # "Annual isolation rates of respiratory viruses, Tecumseh Michigan,
    # USA, 1976-81. Actual rates per 1000 person year"
    source="https://doi.org/10.1017/S0950268800050779",
    start_date="1976",
    end_date="1981",
    country="United States",
    state="Michigan",
    county="Lenawee County",
```

and this

```
    date="2020",
    country="United States",
    state="California",
    county="Los Angeles County",
    source="http://proximityone.com/chartgraphics/pp06037_2020_001.htm",
```
occurs 4 times each.

2023-05-25 15:03 UTC, simonleandergrimm requested changes
Found some additional things to change! Happy to talk this through!

2023-05-25 15:03 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +rhinovirus_old_yearround_study_estimate = (
rename this to `rhinovirus_tecumseh_study_la_estimate`

2023-05-25 15:03 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    # These numbers basically just seem reasonable to me and seem to be
You included this comment twice

2023-05-25 15:03 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +    fall_rhinovirus_incidence_la_county.to_prevalence(
you don't need this, just use `colds_la_county` within `def estimate_prevalences`, and turn it into a prevalence within there.

2023-05-25 15:03 UTC, simonleandergrimm commented on pathogens/rhinovirus.py
> +fall_rhinovirus_incidence_la_county = (
drop this, given our conversation that the fall proportion thing isn't needed

2023-05-25 15:03 UTC, simonleandergrimm requested changes
Found some additional things to change! Happy to talk this through!

2023-05-31 16:20 UTC, simonleandergrimm commented
Superseded by #124 .

2023-05-31 16:20 UTC, closed without merging