Simon hbv
naobservatory/p2ra pull request #71
Opened 2023-05-03 01:32 UTC by simonleandergrimm

I used [2019 estimates for acute Hepatitis B](https://www.cdc.gov/hepatitis/statistics/2019surveillance/Introduction.htm#Technical:~:text=Reported%20cases%20of%20acute,with%20hospitalization%20information%20available).) as the [2020 estimate was impacted by the pandemic](https://www.cdc.gov/hepatitis/statistics/2020surveillance/hepatitis-b.htm#:~:text=During%202020%2C%2044,19%20pandemic.), and later estimates aren't available. 

Before adding more complexity to this estimate (see below), I wanted to get the existing estimate checked by @jeffkaufman 

I added an issue to add spatially resolved Ohio data from 2021, found [here](https://odh.ohio.gov/wps/wcm/connect/gov/9c7b10d8-6d83-42e7-9f18-968c3a26963e/HBV+5+Year+Report+2021.pdf?MOD=AJPERES&CONVERT_TO=url&CACHEID=ROOTWORKSPACE.Z18_K9I401S01H7F40QBNJU3SO1F56-9c7b10d8-6d83-42e7-9f18-968c3a26963e-oqU9kQR?#page=3).

2023-05-03 15:40 UTC, jeffkaufman requested changes
Looks good!

2023-05-03 15:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +    source="https://wonder.cdc.gov/controller/saved/D176/D341F095",
We shouldn't count on a WONDER saved search to persist indefinitely.  If you do keep this variable can you document here what settings you used?

2023-05-03 15:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +hbv_us_2022_deaths_wonder = Number(
It doesn't look like this is used anywhere in your estimate?

2023-05-03 15:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +)
This figure? 

![image](https://user-images.githubusercontent.com/262566/235964781-a246156c-2727-4a49-a5d0-f7756c3ec7a0.png)

Is this saying 2m duration, following a 2m incubation period?

It's suspicious that they show smooth curves crossing an axis break...

2023-05-03 15:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +    source="https://www.cdc.gov/hepatitis/statistics/2019surveillance/Introduction.htm#Technical:~:text=20%2C700%20estimated%20infections%20(95%25%20CI%3A%2011%2C800%E2%80%9350%2C800)",
Add a comment like: `"During 2019, a total of 3,192 acute hepatitis B cases were reported to CDC, resulting in 20,700 estimated infections (95% CI: 11,800–50,800) after adjusting for case underascertainment and underreporting"`

2023-05-03 15:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +    source="https://journals.lww.com/ajg/fulltext/2020/09000/prevalence_of_chronic_hepatitis_b_virus_infection.20.aspx",
The paper has "It is likely that this range represents an underestimation of HBV prevalence because of the noted methodologic limitations. As such, the panel views its estimated US prevalence of chronic HBV to represent a conservative figure which will require modification as further evidence emerges."

We should try to adjust for this, right?

2023-05-03 17:44 UTC, simonleandergrimm commented on pathogens/hbv.py
> +hbv_us_2022_deaths_wonder = Number(
Yes it's not.  After a quick search I didn't fit a case-fatality rate (CFR) for HBV, which made me not use this number any further. 

Should I drop it or do another estimate, putting more time into finding a CFR?

2023-05-03 18:40 UTC, jeffkaufman commented on pathogens/hbv.py
> +hbv_us_2022_deaths_wonder = Number(
I'd add a TODO like you have above for NHANES

2023-05-04 19:59 UTC, jeffkaufman commented
I don't see a response to my `The paper has "It is likely that this range represents an underestimation ..."` comment?

2023-05-04 20:30 UTC, simonleandergrimm commented
> I don't see a response to my `The paper has "It is likely that this range represents an underestimation ..."` comment?

I did answer, try this [link](https://github.com/naobservatory/p2ra/pull/71/files#r1183863572)

2023-05-05 12:39 UTC, jeffkaufman approved these changes

2023-05-05 12:39 UTC, jeffkaufman commented on pathogens/hbv.py
> +)
Thanks, I was misreading it before.  The "HBV DNA" box was what I should have been looking at.

2023-05-05 12:39 UTC, jeffkaufman commented on pathogens/hbv.py
> +    source="https://journals.lww.com/ajg/fulltext/2020/09000/prevalence_of_chronic_hepatitis_b_virus_infection.20.aspx",
I agree, this doesn't add up.  I did some playing with the numbers to see if maybe it would be clear where the difference came from, and their total (1,587,634) is suspiciously close to what you get if you include both "estimate" and "low" for us-born (303,327 + 137,314 + 1,075,069 + 72,014 = 1,587,724).

I think this is worth writing to the authors about to potentially get the paper corrected if it is indeed a mistake; want to draft something or should I?

Separately, I don't see any justification in the paper for why they're using the 'low' for foreign-born instead of 'estimate'?

What if we take their 1.7M and use that as is for now?

2023-05-05 12:52 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    source="https://journals.lww.com/ajg/fulltext/2020/09000/prevalence_of_chronic_hepatitis_b_virus_infection.20.aspx",
> Separately, I don't see any justification in the paper for why they're using the 'low' for foreign-born instead of 'estimate'?

Yeah I also don't see a justification for this.

> I think this is worth writing to the authors about to potentially get the paper corrected if it is indeed a mistake; want to draft something or should I?

 I'll draft something and send it to you for review! 

> What if we take their 1.7M and use that as is for now?

Would you still want to include the lower and upper estimate?

2023-05-05 13:57 UTC, simonleandergrimm commented on pathogens/hbv.py
> +    source="https://journals.lww.com/ajg/fulltext/2020/09000/prevalence_of_chronic_hepatitis_b_virus_infection.20.aspx",
Yes, I'll do that.

2023-05-05 14:45 UTC, simonleandergrimm commented
@jeffkaufman Made the final changes you requested. Shall I merge?

2023-05-05 15:05 UTC, jeffkaufman approved these changes

2023-05-05 15:09 UTC, merged