Asher to prevalence
naobservatory/p2ra pull request #74
Opened 2023-05-03 14:32 UTC by asherps

Added a to_latent_prevalence method to convert from an IncidenceRate to a latent prevalence. Defined a YearsOfInfections object to make this possible. If we know the number of yearly infections and the approximate number of years these infections have been occurring for, we would then be able to convert the annual incidence to a latent prevalence.

2023-05-03 15:25 UTC, jeffkaufman requested changes
Can you say more about how you intend to use this?  I'm nervous about this as a concept because it assumes (a) the incidence rate has been constant over the time period and (b) a constant population (no births, deaths, or migrants).

Happy to call (in person would be better but I'm wfh) if that would be easier?

2023-05-03 15:25 UTC, jeffkaufman commented on .vscode/settings.json
> +}
This doesn't belong in this PR

2023-05-03 15:25 UTC, jeffkaufman commented on pathogen_properties.py
> +            / 365,
Why this factor of 365?

2023-05-11 18:57 UTC, simonleandergrimm commented
I will review this pull request as soon as I/we refocus on vzv, but I don't want it to remain in the PR queue up until then.

2023-05-11 18:57 UTC, closed without merging