Add estimate for influenza
naobservatory/p2ra pull request #85
Opened 2023-05-09 01:28 UTC by jeffkaufman

This follows the same pattern as Norovirus for estimating the short-term incidence of something seasonal: scale an overall estimate that should be reasonably accurate by a more detailed estimate that isn't calibrated.

2023-05-09 01:29 UTC, jeffkaufman commented on pathogen_properties.py
> +                    for i in self.all_inputs | set([self])
While I was in here I noticed and fixed a bug where summarize_location and summarize_date were missing that location/date information could be on the outer variable

2023-05-11 16:14 UTC, asherps approved these changes
This looks great as far as I can tell

2023-05-15 09:53 UTC, simonleandergrimm requested changes
Very nice work! See comments for feedback.

2023-05-15 09:53 UTC, simonleandergrimm commented on pathogens/influenza.py
> +shedding_duration = SheddingDuration(
This isn't fecal shedding, right? If so I would note that. You can also check this paper for more information on shedding of flu in stool: https://twist.com/a/197793/ch/570556/t/4390298/

2023-05-15 09:53 UTC, simonleandergrimm commented on pathogens/influenza.py
> +infections_2019_2020 = IncidenceAbsolute(
There is an uncertainty in the table below: https://www.cdc.gov/flu/about/burden/2019-2020.html#:~:text=All%20ages,(28%2C663%2C846%2C%0A71%2C197%2C342)

2023-05-15 09:53 UTC, simonleandergrimm commented on pathogens/influenza.py
> +infections_2021_2022 = IncidenceAbsolute(
ditto: https://www.cdc.gov/flu/about/burden/2021-2022.htm#:~:text=All%20ages,(7%2C683%2C440%2C%2015%2C541%2C059)

2023-05-15 09:53 UTC, simonleandergrimm commented on pathogens/influenza.py
> +    underreporting_2019_2020 = compare_incidence_to_positive_tests(
Just so I understand this, is this underreporting scalar calculated by comparing overall positive tests in one year with the estimated number of cases in that same year?

2023-05-19 19:16 UTC, jeffkaufman commented on pathogens/influenza.py
> +shedding_duration = SheddingDuration(
added todo

2023-05-19 19:16 UTC, jeffkaufman commented on pathogens/influenza.py
> +infections_2019_2020 = IncidenceAbsolute(
awesome, thanks!  added

2023-05-19 19:16 UTC, jeffkaufman commented on pathogens/influenza.py
> +infections_2021_2022 = IncidenceAbsolute(
added

2023-05-19 19:16 UTC, jeffkaufman commented on pathogens/influenza.py
> +    underreporting_2019_2020 = compare_incidence_to_positive_tests(
yes

2023-05-23 18:10 UTC, merged