Simon hcv
naobservatory/p2ra pull request #90
Opened 2023-05-11 14:09 UTC by simonleandergrimm

2023-05-11 16:17 UTC, jeffkaufman requested changes

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +    end_date="2016",
Is it possible to get a `Prevalence` instead of `PrevalenceAbsolute` from the paper, since they say they calculate a relative prevalence as an intermediate step?

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +    source="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122232#:~:text=Median%20HCV%20RNA%20levels%20initially%20diverged%20at%20three%20months%20following%20infection",
This wasn't fecal sampling, right?  Can you at least say what sampling strategy they used?

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +    # infections (95% bootstrap CI: 11.0–47.4).
include `confidence_interval` and `confidence_probability` since we have them

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +                    case_rate.to_prevalence(shedding_duration).__mul__(
Instead of `__mul__` you just do `*`

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +}
How about organizing this as: county -> year -> {total, acute}?

```
{'Franklin': {2020: {'acute': 0.8, 'total': 74.3},
              2021: {'acute': 1.5, 'total': 86.8}},
 'Greene': {2020: {'acute': 0.0, 'total': 74.1},
            2021: {'acute': 0.6, 'total': 49.4}},
 'Lawrence': {2020: {'acute': 15.2, 'total': 367.2},
              2021: {'acute': 1.7, 'total': 379.1}},
 'Licking': {2020: {'acute': 3.4, 'total': 59.5},
             2021: {'acute': 2.2, 'total': 65.1}},
 'Lucas': {2020: {'acute': 0.7, 'total': 134.7},
           2021: {'acute': 0.2, 'total': 122.1}},
 'Montgomery': {2020: {'acute': 0.6, 'total': 105.9},
                2021: {'acute': 0.4, 'total': 98.0}},
 'Sandusky': {2020: {'acute': 1.7, 'total': 104.5},
              2021: {'acute': 0.0, 'total': 102.8}},
 'Summit': {2020: {'acute': 1.1, 'total': 99.7},
            2021: {'acute': 0.7, 'total': 97.2}},
 'Trumbull': {2020: {'acute': 6.1, 'total': 120.9},
              2021: {'acute': 1.0, 'total': 107.2}}}
```

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +        counter = -1
This would all be a lot clearer if rewritten to match my proposal for `ohio_counties_case_counts` above

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +    for key in ohio_counties_case_counts:
instead of `key` how about `county`?

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +                    annual_infections_per_100k=ohio_counties_case_counts[key][
Are these case counts or case rates?

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +        reported_acute_ohio_2020.to_prevalence(shedding_duration).__mul__(
`*`

2023-05-11 16:17 UTC, jeffkaufman commented on pathogens/hcv.py
> +        reported_acute_ohio_2021.to_prevalence(shedding_duration).__mul__(
`*`

2023-05-11 17:06 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    end_date="2016",
They do provide a Prevalence, thanks for spotting this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6719781/#:~:text=(1%2C983%2C900%2D2%2C807%2C800)-,1.0%25,(0.8%25%2D1.1%25),-Open%20in%20a

2023-05-11 17:08 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    end_date="2016",
I added their note on which population they used, and changed the date of the estimate to 2016:
```
To calculate the number of noninstitutionalized civilians in the United States with HCV antibody and HCV RNA during 2013-2016, prevalence estimates were then multiplied by the estimated total noninstitutionalized civilian adult U.S. population as of December 31, 2016 from the 2012-2016 ACS. 
```

2023-05-11 17:36 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    source="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122232#:~:text=Median%20HCV%20RNA%20levels%20initially%20diverged%20at%20three%20months%20following%20infection",
It isn't fecal sampling, those are HCV RNA levels in blood.

I looked into this some more. I didn't find longitudinal sampling of HCV RNA in stool, but I found a [different study](https://academic.oup.com/cid/article/64/3/284/2452663#:~:text=Detection%20of%20HCV%20in%20rectal%20fluid%20as%20a%20function%20of%20HCV%20VL%20in%20blood.), stating that HCV RNA in rectal fluid is more common among patients with elevated HCV RNA blood levels.
<img width="675" alt="image" src="https://github.com/naobservatory/p2ra/assets/58591538/182f0402-cdff-4efb-b238-f16fe0b0f8b5">

2023-05-11 17:38 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    source="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122232#:~:text=Median%20HCV%20RNA%20levels%20initially%20diverged%20at%20three%20months%20following%20infection",
Flagging that this does feel like I want to prove that non-fecal shedding data can be used.

2023-05-11 19:57 UTC, jeffkaufman approved these changes

2023-05-11 19:57 UTC, jeffkaufman commented on pathogens/hcv.py
> +    source="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122232#:~:text=Median%20HCV%20RNA%20levels%20initially%20diverged%20at%20three%20months%20following%20infection",
"Flagging that this does feel like I want to prove that non-fecal shedding data can be used."

Not sure what you mean by this?

The general idea for using fecal shedding in our shedding duration (with potentially other forms of shedding as a proxy) is that to build a model we want something that should be directly proportional to relative abundance.

2023-05-11 19:57 UTC, jeffkaufman commented on pathogens/hcv.py
> +    # persistent infection.
For now, how about saying that we're using blood detectability duration as a proxy for fecal detectability duration?

2023-05-12 20:12 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    # persistent infection.
Added that comment.

2023-05-12 20:14 UTC, simonleandergrimm commented on pathogens/hcv.py
> +    source="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122232#:~:text=Median%20HCV%20RNA%20levels%20initially%20diverged%20at%20three%20months%20following%20infection",
I was getting at the fact that I have the incentive to keep using the blood HCV RNA data, and this piece of evidence on a link between fecal and blood HCV RNA levels makes it easier for me to keep using said data. I might have found a different piece of evidence, had I gone into this with a different motivation.

2023-05-14 17:35 UTC, merged