Asher ebv denmark
naobservatory/p2ra pull request #94
Opened 2023-05-11 17:54 UTC by asherps

Estimate for EBV's prevalence in Denmark using a 1983 EBV seroprevalence study from Denmark.

2023-05-12 19:53 UTC, simonleandergrimm requested changes
Suggested some changes to make the Denmark estimate cleaner and use less manual data parsing (i.e., reading in the population structure of DK manually). After going over my changes you can assign the PR to be reviewed by Jeff.

2023-05-12 19:53 UTC, simonleandergrimm commented on pathogens/EBV.py
> +    source="10.3109/inf.1983.15.issue-4.03",
mention the specific part of the paper you are referring to.

2023-05-12 19:53 UTC, simonleandergrimm commented on pathogens/EBV.py
> +)
Instead of scalars, these populations should be `Population`. The data structure to use here is the following ([from hsv_2](https://github.com/naobservatory/p2ra/blob/main/pathogens/hsv_2.py#L54)): 
```
stratified_us_pop = {
    "15-19": Population(
        people=21_445_493,
        date="2018",
        country="United States",
        source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
        tag="15-19yo",
    ),
    "20-24": Population(
        people=21_717_962,
        date="2018",
        country="United States",
        source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
        tag="20-24yo",
    ),
    "25-34": Population(
        people=45_344_674,
        date="2018",
        country="United States",
        source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
        tag="25-34yo",
    ),
    "35-44": Population(
        people=41_498_453,
        date="2018",
        country="United States",
        source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
        tag="35-44yo",
    ),
    "45-54": Population(
        people=41_605_244,
        date="2018",
        country="United States",
        source="https://data.census.gov/table?q=2018+us+population&t=Civilian+Population",
        tag="45-54yo",
    ),
}

us_population_2018_18_to_49yo = Population(
    people=stratified_us_pop["15-19"].people * 0.6
    + stratified_us_pop["20-24"].people
    + stratified_us_pop["25-34"].people
    + stratified_us_pop["35-44"].people
    + stratified_us_pop["45-54"].people * 0.5,
    date="2018",
    country="United States",
    tag="18-49yo",
    inputs=list(stratified_us_pop.values()),
)
```

2023-05-16 20:51 UTC, asherps commented
Hey Jeff, I assigned this PR to you since Simon is out of office. I fixed all of Simon's requests. There is still one bug in the code that I don't quite understand, when I try to create a dictionary of population objects and add populations from the CSV to them (dataclasses.FrozenInstanceError: cannot assign to field 'people'). Do you have any idea how to fix this?

2023-05-17 14:17 UTC, jeffkaufman requested changes

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +nhanes_age_8_19_estimate = Prevalence(
This is actually 6-19: "Epstein-Barr seroprevalence among US children, ages 6–19, 2003–2010."

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    country="United States",
Add `coverage_probability=0.95`, since this says `95% CI`

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    start_date="2003",
Dowd has:
```
confidence_interval=(0.80 * 100_000, 0.859 * 100_000)
coverage_probability=0.95
```

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    infections_per_100k=0.89 * 100_000,
I see `82.90` in Dowd above; why the switch to Balfour?  Which paper do you think is better?

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +us_seroprevalence_2003_2010 = nhanes_18_19_yo_estimate * (
How about adding `Prevalence.weightedAverageByPopulation(...)`?  And then your `Scalar`s can be Populations?

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +
```
else:
   assert False
```

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +}
This doesn't work because you can't modify a variable after creating it (it's frozen).  Instead, how about:

```
denmark_age_groups = Counter()
...
         elif 4 <= age <= 14:
            denmark_age_groups[4, 14].people += population...
...
denmark_populations = {}
for (min_age, max_age), people in denmark_age_groups.items():
    denmark_populations[min_age, max_age] = Population(
        people=people,
        date="2023",
        country="Denmark",
        tag="%s-%s" % (min_age, max_age),
    )
```

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +denmark_seroprevalence = PrevalenceAbsolute(
```
denmark_seroprevalences = {
    ...
    (4, 14): Prevalence(
        date="2023",
        country="Denmark",
        active=Active.LATENT,
        date=1983,
        # See page 336 of the study (page 3 of the pdf)
        source="10.3109/inf.1983.15.issue-4.03",
    ),
    ...
}

...

denmark_overall_seroprevalence = Prevalence.weightedAverageByPopulation(
   ...
   (denmark_seroprevalences[4,14], denmark_populations[4, 14]),
   ...
)
```

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +    ]
I don't see the NHANES estimate?

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +# Open the CSV file
`# Open the CSV file` is not a useful comment

2023-05-17 14:17 UTC, jeffkaufman commented on pathogens/EBV.py
> +with open(prevalence_data_filename("DenmarkPopulationData.csv")) as file:
Add a comment saying where `DenmarkPopulationData.csv` came from

2023-05-17 15:25 UTC, asherps commented on pathogens/EBV.py
> +    ]
The NHANES estimate is incorporated into us_seroprevalence_2003_2010. I could also return the UK prevalence if this might be helpful

2023-05-18 13:53 UTC, jeffkaufman requested changes
Nearly ready to go in!

2023-05-18 13:53 UTC, jeffkaufman commented on pathogens/EBV.py
> +        population = float(row[5].replace(" ", ""))
If you're going to turn it into an int below, why not just do it here?

2023-05-18 13:53 UTC, jeffkaufman commented on pathogens/EBV.py
> +            tag="%s-%syo" % (min_age, max_age),
I don't think you need to be setting a tag?

2023-05-18 13:53 UTC, jeffkaufman commented on pathogens/EBV.py
> +    print(denmark_populations[0, 0])
rm

2023-05-18 13:53 UTC, jeffkaufman commented on test.py
> +                people=100_000 * i, date="2000-01-0%s" % i, tag="US-2020"
don't need the tag

2023-05-18 13:53 UTC, jeffkaufman commented on test.py
> +            delta=0.00001,
I think you can leave off the delta?

2023-05-18 14:29 UTC, asherps commented on test.py
> +                people=100_000 * i, date="2000-01-0%s" % i, tag="US-2020"
When I remove it, I get TypeError: Population.__init__() missing 1 required keyword-only argument: 'tag'

2023-05-18 14:33 UTC, asherps commented
For some reason, ./summarize.py does not display the country name or dates for this file on my computer. I don't know why

2023-05-19 19:07 UTC, jeffkaufman commented
Looks like this still needs a merge from main?

2023-05-23 15:04 UTC, simonleandergrimm commented
@asherps This still needs a merge from main, we can look into this in a second.

2023-05-23 19:03 UTC, jeffkaufman commented on pathogen_properties.py
> +            date_source=self,
location_source=self

2023-05-23 19:03 UTC, jeffkaufman commented on pathogen_properties.py
> +            date_source=self,
location_source=self

2023-05-23 19:07 UTC, jeffkaufman requested changes
getting close!

2023-05-23 19:07 UTC, jeffkaufman commented on pathogen_properties.py
> +            )
I thought I already commented on this, but why are you dividing by 100k and then multiplying again?

Also, I think you can use `np.average(vals, weights)`:
```
        return dataclasses.replace(
            pairs[0][0],
            infections_per_100k=np.average(
               [prevalence.infections_per_100k for prevalence, population in pairs],
               weights=[population.people for prevalence, population in pairs]
            )
        )
```

2023-05-23 19:07 UTC, jeffkaufman commented on pathogens/EBV.py
> +    tag="Denmark-2023",
Instead of a `tag` use `country="..."` and `date=...`

2023-05-23 19:07 UTC, jeffkaufman commented on pathogens/EBV.py
> +denmark_population = Population(
Is this actually used?

2023-05-23 19:37 UTC, asherps commented on pathogen_properties.py
> +            )
This was so the variable names were accurate (totalInfections would actually represent total infections and not total infections * 100,000, which is a weird thing to name a variable for). Np.average is cleaner, though, thanks!

2023-05-24 02:11 UTC, jeffkaufman requested changes

2023-05-24 02:11 UTC, jeffkaufman commented on .gitignore
> -
Why are you removing `settings.json` from `.gitignore`?

2023-05-24 02:11 UTC, jeffkaufman commented on pathogens/EBV.py
> +    tag="US-2022",
This tag should be something like `under-18`.  That it's for 2022 is already in the `date`, and that it's for the US should be `country="United States"`

2023-05-24 02:11 UTC, jeffkaufman commented on pathogens/EBV.py
> +    tag="US-2022",
ditto

2023-05-24 02:11 UTC, jeffkaufman commented on pathogens/EBV.py
> +under_18_population_US = Population(
How about:

```
us_fraction_under_18 = Scalar(
   scalar=.222,
   date="2022",
   source="https://www.census.gov/quickfacts/fact/table/US",
)

under_18_population_US = us_population(year=2022) * us_fraction_under_18
over_18_population_US = us_population(year=2022) - under_18_population_US
```

2023-05-24 02:11 UTC, jeffkaufman commented on pathogens/EBV.py
> +denmark_age_groups: Counter[tuple[int, int]] = Counter()
```
# (min_age, max_age) -> people within that age range
```

2023-05-24 18:23 UTC, asherps commented on .gitignore
> -
It's already there underneath, at least on my computer

2023-05-24 20:02 UTC, simonleandergrimm reviewed
This looks good now, though there are still some changes that are in this branch, although they look like they should belong in the main EBV branch. I believe this is fine for now, but normally shouldn't be done as it's confusing for reviewers

2023-05-24 20:08 UTC, simonleandergrimm approved these changes
Currently failing checks, once that is fixed it can be pulled into `asher_EBV`!

2023-05-25 19:34 UTC, merged